<?php

use Illuminate\Database\Seeder;
use App\City;

class CityTableSeeder extends Seeder
{
	public function run()
	{
		City::insert([
			['id' => 5, 'name' => 'Caloocan', 'province_id' => 121],
			['id' => 6, 'name' => 'Las Pinas', 'province_id' => 121],
			['id' => 7, 'name' => 'Makati', 'province_id' => 121],
			['id' => 8, 'name' => 'Malabon', 'province_id' => 121],
			['id' => 9, 'name' => 'Mandaluyong', 'province_id' => 121],
			['id' => 10, 'name' => 'Manila', 'province_id' => 121],
			['id' => 11, 'name' => 'Marikina', 'province_id' => 121],
			['id' => 12, 'name' => 'Muntinlupa', 'province_id' => 121],
			['id' => 13, 'name' => 'Navotas', 'province_id' => 121],
			['id' => 14, 'name' => 'Paranaque', 'province_id' => 121],
			['id' => 15, 'name' => 'Pasay', 'province_id' => 121],
			['id' => 16, 'name' => 'Pasig', 'province_id' => 121],
			['id' => 17, 'name' => 'Pateros', 'province_id' => 121],
			['id' => 18, 'name' => 'Quezon City', 'province_id' => 121],
			['id' => 19, 'name' => 'San Juan', 'province_id' => 121],
			['id' => 20, 'name' => 'Taguig', 'province_id' => 121],
			['id' => 21, 'name' => 'Valuenzuela', 'province_id' => 121],
			['id' => 22, 'name' => 'Bangued', 'province_id' => 20],
			['id' => 23, 'name' => 'Boliney', 'province_id' => 20],
			['id' => 24, 'name' => 'Bucay', 'province_id' => 20],
			['id' => 25, 'name' => 'Bucloc', 'province_id' => 20],
			['id' => 26, 'name' => 'Daguioman', 'province_id' => 20],
			['id' => 27, 'name' => 'Danglas', 'province_id' => 20],
			['id' => 28, 'name' => 'Dolores', 'province_id' => 20],
			['id' => 29, 'name' => 'La Paz', 'province_id' => 20],
			['id' => 30, 'name' => 'Lacub', 'province_id' => 20],
			['id' => 31, 'name' => 'Lagangilang', 'province_id' => 20],
			['id' => 32, 'name' => 'Lagayan', 'province_id' => 20],
			['id' => 33, 'name' => 'Langiden', 'province_id' => 20],
			['id' => 34, 'name' => 'Licuan-Baay (Licuan)', 'province_id' => 20],
			['id' => 35, 'name' => 'Luba', 'province_id' => 20],
			['id' => 36, 'name' => 'Malibcong', 'province_id' => 20],
			['id' => 37, 'name' => 'Manabo', 'province_id' => 20],
			['id' => 38, 'name' => 'Penarrubia', 'province_id' => 20],
			['id' => 39, 'name' => 'Pidigan', 'province_id' => 20],
			['id' => 40, 'name' => 'Pilar', 'province_id' => 20],
			['id' => 41, 'name' => 'Sallapadan', 'province_id' => 20],
			['id' => 42, 'name' => 'San Isidro', 'province_id' => 20],
			['id' => 43, 'name' => 'San Juan', 'province_id' => 20],
			['id' => 44, 'name' => 'San Quintin', 'province_id' => 20],
			['id' => 45, 'name' => 'Tayum', 'province_id' => 20],
			['id' => 46, 'name' => 'Tineg', 'province_id' => 20],
			['id' => 47, 'name' => 'Tubo', 'province_id' => 20],
			['id' => 48, 'name' => 'Villaviciosa', 'province_id' => 20],
			['id' => 49, 'name' => 'Apayao', 'province_id' => 19],
			['id' => 50, 'name' => 'Baguio', 'province_id' => 21],
			['id' => 51, 'name' => 'Benguet', 'province_id' => 22],
			['id' => 52, 'name' => 'Aguinaldo', 'province_id' => 23],
			['id' => 53, 'name' => 'Alfonso Lista', 'province_id' => 23],
			['id' => 54, 'name' => 'Asipulo', 'province_id' => 23],
			['id' => 55, 'name' => 'Banaue', 'province_id' => 23],
			['id' => 56, 'name' => 'Hingyon', 'province_id' => 23],
			['id' => 57, 'name' => 'Hungduan', 'province_id' => 23],
			['id' => 58, 'name' => 'Kiangan', 'province_id' => 23],
			['id' => 59, 'name' => 'Lagawe', 'province_id' => 23],
			['id' => 60, 'name' => 'Lamut', 'province_id' => 23],
			['id' => 61, 'name' => 'Mayoyao', 'province_id' => 23],
			['id' => 62, 'name' => 'Tinoc', 'province_id' => 23],
			['id' => 63, 'name' => 'Balbalan', 'province_id' => 24],
			['id' => 64, 'name' => 'Lubuagan', 'province_id' => 24],
			['id' => 65, 'name' => 'Pasil', 'province_id' => 24],
			['id' => 66, 'name' => 'Pinukpuk', 'province_id' => 24],
			['id' => 67, 'name' => 'Rizal', 'province_id' => 24],
			['id' => 68, 'name' => 'Tanudan', 'province_id' => 24],
			['id' => 69, 'name' => 'Tinglayan', 'province_id' => 24],
			['id' => 70, 'name' => 'Barlig', 'province_id' => 18],
			['id' => 71, 'name' => 'Bauko', 'province_id' => 18],
			['id' => 72, 'name' => 'Besao', 'province_id' => 18],
			['id' => 73, 'name' => 'Bontoc', 'province_id' => 18],
			['id' => 74, 'name' => 'Natonin', 'province_id' => 18],
			['id' => 75, 'name' => 'Paracelis', 'province_id' => 18],
			['id' => 76, 'name' => 'Sabangan', 'province_id' => 18],
			['id' => 77, 'name' => 'Sadanga', 'province_id' => 18],
			['id' => 78, 'name' => 'Sagada', 'province_id' => 18],
			['id' => 79, 'name' => 'Tadian', 'province_id' => 18],
			['id' => 80, 'name' => 'Alaminos', 'province_id' => 25],
			['id' => 81, 'name' => 'Dagupan', 'province_id' => 25],
			['id' => 82, 'name' => 'San Carlos', 'province_id' => 25],
			['id' => 83, 'name' => 'Urdaneta', 'province_id' => 25],
			['id' => 84, 'name' => 'Agno', 'province_id' => 25],
			['id' => 85, 'name' => 'Aguilar', 'province_id' => 25],
			['id' => 86, 'name' => 'Alcala', 'province_id' => 25],
			['id' => 87, 'name' => 'Anda', 'province_id' => 25],
			['id' => 88, 'name' => 'Asingan', 'province_id' => 25],
			['id' => 89, 'name' => 'Balungao', 'province_id' => 25],
			['id' => 90, 'name' => 'Bani', 'province_id' => 25],
			['id' => 91, 'name' => 'Basista', 'province_id' => 25],
			['id' => 92, 'name' => 'Bautista', 'province_id' => 25],
			['id' => 93, 'name' => 'Bayambang', 'province_id' => 25],
			['id' => 94, 'name' => 'Binalonan', 'province_id' => 25],
			['id' => 95, 'name' => 'Binmaley', 'province_id' => 25],
			['id' => 96, 'name' => 'Bolinao', 'province_id' => 25],
			['id' => 97, 'name' => 'Bugallon', 'province_id' => 25],
			['id' => 98, 'name' => 'Burgos', 'province_id' => 25],
			['id' => 99, 'name' => 'Calasiao', 'province_id' => 25],
			['id' => 100, 'name' => 'Dasol', 'province_id' => 25],
			['id' => 101, 'name' => 'Infanta', 'province_id' => 25],
			['id' => 102, 'name' => 'Labrador', 'province_id' => 25],
			['id' => 103, 'name' => 'Laoac', 'province_id' => 25],
			['id' => 104, 'name' => 'Lingayen', 'province_id' => 25],
			['id' => 105, 'name' => 'Mabini', 'province_id' => 25],
			['id' => 106, 'name' => 'Malasiqui', 'province_id' => 25],
			['id' => 107, 'name' => 'Manaoag', 'province_id' => 25],
			['id' => 108, 'name' => 'Mangaldan', 'province_id' => 25],
			['id' => 109, 'name' => 'Mangatarem', 'province_id' => 25],
			['id' => 110, 'name' => 'Mapandan', 'province_id' => 25],
			['id' => 111, 'name' => 'Natividad', 'province_id' => 25],
			['id' => 112, 'name' => 'Pozorrubio', 'province_id' => 25],
			['id' => 113, 'name' => 'Rosales', 'province_id' => 25],
			['id' => 114, 'name' => 'San Fabian', 'province_id' => 25],
			['id' => 115, 'name' => 'San Jacinto', 'province_id' => 25],
			['id' => 116, 'name' => 'San Manuel', 'province_id' => 25],
			['id' => 117, 'name' => 'San Nicolas', 'province_id' => 25],
			['id' => 118, 'name' => 'San Quintin', 'province_id' => 25],
			['id' => 119, 'name' => 'Santa Barbara', 'province_id' => 25],
			['id' => 120, 'name' => 'Santa Maria', 'province_id' => 25],
			['id' => 121, 'name' => 'Santo Tomas', 'province_id' => 25],
			['id' => 122, 'name' => 'Sison', 'province_id' => 25],
			['id' => 123, 'name' => 'Sual', 'province_id' => 25],
			['id' => 124, 'name' => 'Tayug', 'province_id' => 25],
			['id' => 125, 'name' => 'Umingan', 'province_id' => 25],
			['id' => 126, 'name' => 'Urbiztondo', 'province_id' => 25],
			['id' => 127, 'name' => 'Villasis', 'province_id' => 25],
			['id' => 128, 'name' => 'Adams', 'province_id' => 28],
			['id' => 129, 'name' => 'Bacarra', 'province_id' => 28],
			['id' => 130, 'name' => 'Badoc', 'province_id' => 28],
			['id' => 131, 'name' => 'Bangui', 'province_id' => 28],
			['id' => 132, 'name' => 'Banna (Espiritu)', 'province_id' => 28],
			['id' => 133, 'name' => 'Batac City', 'province_id' => 28],
			['id' => 134, 'name' => 'Burgos', 'province_id' => 28],
			['id' => 135, 'name' => 'Carasi', 'province_id' => 28],
			['id' => 136, 'name' => 'Currimao', 'province_id' => 28],
			['id' => 137, 'name' => 'Dingras', 'province_id' => 28],
			['id' => 138, 'name' => 'Dumalneg', 'province_id' => 28],
			['id' => 139, 'name' => 'Laoag City', 'province_id' => 28],
			['id' => 140, 'name' => 'Marcos', 'province_id' => 28],
			['id' => 141, 'name' => 'Nueva Era', 'province_id' => 28],
			['id' => 142, 'name' => 'Pagudpud', 'province_id' => 28],
			['id' => 143, 'name' => 'Paoay', 'province_id' => 28],
			['id' => 144, 'name' => 'Pasuquin', 'province_id' => 28],
			['id' => 145, 'name' => 'Piddig', 'province_id' => 28],
			['id' => 146, 'name' => 'Pinili', 'province_id' => 28],
			['id' => 147, 'name' => 'San Nicolas', 'province_id' => 28],
			['id' => 148, 'name' => 'Sarrat', 'province_id' => 28],
			['id' => 149, 'name' => 'Solsona', 'province_id' => 28],
			['id' => 150, 'name' => 'Vintar', 'province_id' => 28],
			['id' => 151, 'name' => 'Vigan City', 'province_id' => 27],
			['id' => 152, 'name' => 'Candon City', 'province_id' => 27],
			['id' => 153, 'name' => 'Alilem', 'province_id' => 27],
			['id' => 154, 'name' => 'Banayoyo', 'province_id' => 27],
			['id' => 155, 'name' => 'Bantay', 'province_id' => 27],
			['id' => 156, 'name' => 'Burgos', 'province_id' => 27],
			['id' => 157, 'name' => 'Cabugao', 'province_id' => 27],
			['id' => 158, 'name' => 'Caoayan', 'province_id' => 27],
			['id' => 159, 'name' => 'Cervantes', 'province_id' => 27],
			['id' => 160, 'name' => 'Galimuyod', 'province_id' => 27],
			['id' => 161, 'name' => 'Gregorio del Pilar (Concepcion)', 'province_id' => 27],
			['id' => 162, 'name' => 'Lidlidda', 'province_id' => 27],
			['id' => 163, 'name' => 'Magsingal', 'province_id' => 27],
			['id' => 164, 'name' => 'Nagbukel', 'province_id' => 27],
			['id' => 165, 'name' => 'Narvacan', 'province_id' => 27],
			['id' => 166, 'name' => 'Quirino (Angaki)', 'province_id' => 27],
			['id' => 167, 'name' => 'Salcedo (Baugen)', 'province_id' => 27],
			['id' => 168, 'name' => 'San Emilio', 'province_id' => 27],
			['id' => 169, 'name' => 'San Esteban', 'province_id' => 27],
			['id' => 170, 'name' => 'San Ildefonso', 'province_id' => 27],
			['id' => 171, 'name' => 'San Juan (Lapog)', 'province_id' => 27],
			['id' => 172, 'name' => 'San Vicente', 'province_id' => 27],
			['id' => 173, 'name' => 'Santa', 'province_id' => 27],
			['id' => 174, 'name' => 'Santa Catalina', 'province_id' => 27],
			['id' => 175, 'name' => 'Santa Cruz', 'province_id' => 27],
			['id' => 176, 'name' => 'Santa Lucia', 'province_id' => 27],
			['id' => 177, 'name' => 'Santa Maria', 'province_id' => 27],
			['id' => 178, 'name' => 'Santiago', 'province_id' => 27],
			['id' => 179, 'name' => 'Santo Domingo', 'province_id' => 27],
			['id' => 180, 'name' => 'Sigay', 'province_id' => 27],
			['id' => 181, 'name' => 'Sinait', 'province_id' => 27],
			['id' => 182, 'name' => 'Sugpon', 'province_id' => 27],
			['id' => 183, 'name' => 'Suyo', 'province_id' => 27],
			['id' => 184, 'name' => 'Tagudin', 'province_id' => 27],
			['id' => 185, 'name' => 'San Fernando City', 'province_id' => 26],
			['id' => 186, 'name' => 'Agoo', 'province_id' => 26],
			['id' => 187, 'name' => 'Aringay', 'province_id' => 26],
			['id' => 188, 'name' => 'Bacnotan', 'province_id' => 26],
			['id' => 189, 'name' => 'Bagulin', 'province_id' => 26],
			['id' => 190, 'name' => 'Balaoan', 'province_id' => 26],
			['id' => 191, 'name' => 'Bangar', 'province_id' => 26],
			['id' => 192, 'name' => 'Bauang', 'province_id' => 26],
			['id' => 193, 'name' => 'Burgos', 'province_id' => 26],
			['id' => 194, 'name' => 'Caba', 'province_id' => 26],
			['id' => 195, 'name' => 'Luna', 'province_id' => 26],
			['id' => 196, 'name' => 'Naguilian', 'province_id' => 26],
			['id' => 197, 'name' => 'Pugo', 'province_id' => 26],
			['id' => 198, 'name' => 'Rosario', 'province_id' => 26],
			['id' => 199, 'name' => 'San Gabriel', 'province_id' => 26],
			['id' => 200, 'name' => 'San Juan', 'province_id' => 26],
			['id' => 201, 'name' => 'Sto. Tomas', 'province_id' => 26],
			['id' => 202, 'name' => 'Santol', 'province_id' => 26],
			['id' => 203, 'name' => 'Sudipen', 'province_id' => 26],
			['id' => 204, 'name' => 'Tubao', 'province_id' => 26],
			['id' => 205, 'name' => 'Basco', 'province_id' => 29],
			['id' => 206, 'name' => 'Itbayat', 'province_id' => 29],
			['id' => 207, 'name' => 'Ivana', 'province_id' => 29],
			['id' => 208, 'name' => 'Mahatao', 'province_id' => 29],
			['id' => 209, 'name' => 'Sabtang', 'province_id' => 29],
			['id' => 210, 'name' => 'Uyugan', 'province_id' => 29],
			['id' => 211, 'name' => 'Tuguegarao City', 'province_id' => 30],
			['id' => 212, 'name' => 'Abulug', 'province_id' => 30],
			['id' => 213, 'name' => 'Alcala', 'province_id' => 30],
			['id' => 214, 'name' => 'Allacapan', 'province_id' => 30],
			['id' => 215, 'name' => 'Amulung', 'province_id' => 30],
			['id' => 216, 'name' => 'Aparri', 'province_id' => 30],
			['id' => 217, 'name' => 'Baggao', 'province_id' => 30],
			['id' => 218, 'name' => 'Ballesteros', 'province_id' => 30],
			['id' => 219, 'name' => 'Buguey', 'province_id' => 30],
			['id' => 220, 'name' => 'Calayan', 'province_id' => 30],
			['id' => 221, 'name' => 'Camalaniugan', 'province_id' => 30],
			['id' => 222, 'name' => 'Claveria', 'province_id' => 30],
			['id' => 223, 'name' => 'Enrile', 'province_id' => 30],
			['id' => 224, 'name' => 'Gattaran', 'province_id' => 30],
			['id' => 225, 'name' => 'Gonzaga', 'province_id' => 30],
			['id' => 226, 'name' => 'Iguig', 'province_id' => 30],
			['id' => 227, 'name' => 'Lal-Lo', 'province_id' => 30],
			['id' => 228, 'name' => 'Lasam', 'province_id' => 30],
			['id' => 229, 'name' => 'Pamplona', 'province_id' => 30],
			['id' => 230, 'name' => 'Peñablanca', 'province_id' => 30],
			['id' => 231, 'name' => 'Piat', 'province_id' => 30],
			['id' => 232, 'name' => 'Rizal', 'province_id' => 30],
			['id' => 233, 'name' => 'Sanchez-Mira', 'province_id' => 30],
			['id' => 234, 'name' => 'Santa Ana', 'province_id' => 30],
			['id' => 235, 'name' => 'Santa Praxedes', 'province_id' => 30],
			['id' => 236, 'name' => 'Santa Teresita', 'province_id' => 30],
			['id' => 237, 'name' => 'Santo Niño (Faire)', 'province_id' => 30],
			['id' => 238, 'name' => 'Solana', 'province_id' => 30],
			['id' => 239, 'name' => 'Tuao', 'province_id' => 30],
			['id' => 240, 'name' => 'Santiago', 'province_id' => 34],
			['id' => 241, 'name' => 'Cauayan City1', 'province_id' => 31],
			['id' => 242, 'name' => 'Ilagan City2', 'province_id' => 31],
			['id' => 243, 'name' => 'Santiago City3', 'province_id' => 31],
			['id' => 244, 'name' => 'Alicia', 'province_id' => 31],
			['id' => 245, 'name' => 'Angadanan', 'province_id' => 31],
			['id' => 246, 'name' => 'Aurora', 'province_id' => 31],
			['id' => 247, 'name' => 'Benito Soliven', 'province_id' => 31],
			['id' => 248, 'name' => 'Burgos', 'province_id' => 31],
			['id' => 249, 'name' => 'Cabagan', 'province_id' => 31],
			['id' => 250, 'name' => 'Cabatuan', 'province_id' => 31],
			['id' => 251, 'name' => 'Cordon', 'province_id' => 31],
			['id' => 252, 'name' => 'Delfin Albano', 'province_id' => 31],
			['id' => 253, 'name' => 'Dinapigue', 'province_id' => 31],
			['id' => 254, 'name' => 'Divilican', 'province_id' => 31],
			['id' => 255, 'name' => 'Echague', 'province_id' => 31],
			['id' => 256, 'name' => 'Gamu', 'province_id' => 31],
			['id' => 257, 'name' => 'Jones', 'province_id' => 31],
			['id' => 258, 'name' => 'Luna', 'province_id' => 31],
			['id' => 259, 'name' => 'Maconacon', 'province_id' => 31],
			['id' => 260, 'name' => 'Mallig', 'province_id' => 31],
			['id' => 261, 'name' => 'Naguilian', 'province_id' => 31],
			['id' => 262, 'name' => 'Palanan', 'province_id' => 31],
			['id' => 263, 'name' => 'Quezon', 'province_id' => 31],
			['id' => 264, 'name' => 'Alfonso Castañeda', 'province_id' => 32],
			['id' => 265, 'name' => 'Ambaguio', 'province_id' => 32],
			['id' => 266, 'name' => 'Aritao', 'province_id' => 32],
			['id' => 267, 'name' => 'Bagabag', 'province_id' => 32],
			['id' => 268, 'name' => 'Bambang', 'province_id' => 32],
			['id' => 269, 'name' => 'Bayombong', 'province_id' => 32],
			['id' => 270, 'name' => 'Diadi', 'province_id' => 32],
			['id' => 271, 'name' => 'Dupax del Norte', 'province_id' => 32],
			['id' => 272, 'name' => 'Dupax del Sur', 'province_id' => 32],
			['id' => 273, 'name' => 'Kasibu', 'province_id' => 32],
			['id' => 274, 'name' => 'Kayapa', 'province_id' => 32],
			['id' => 275, 'name' => 'Quezon', 'province_id' => 32],
			['id' => 276, 'name' => 'Santa Fe', 'province_id' => 32],
			['id' => 277, 'name' => 'Solano', 'province_id' => 32],
			['id' => 278, 'name' => 'Aglipay', 'province_id' => 33],
			['id' => 279, 'name' => 'Cabarroguis', 'province_id' => 33],
			['id' => 280, 'name' => 'Diffun', 'province_id' => 33],
			['id' => 281, 'name' => 'Maddela', 'province_id' => 33],
			['id' => 282, 'name' => 'Nagtipunan', 'province_id' => 33],
			['id' => 283, 'name' => 'Saguday', 'province_id' => 33],
			['id' => 284, 'name' => 'Angeles City', 'province_id' => 35],
			['id' => 285, 'name' => 'Baler', 'province_id' => 36],
			['id' => 286, 'name' => 'Casiguran', 'province_id' => 36],
			['id' => 287, 'name' => 'Dilasag', 'province_id' => 36],
			['id' => 288, 'name' => 'Dinalungan', 'province_id' => 36],
			['id' => 289, 'name' => 'Dingalan', 'province_id' => 36],
			['id' => 290, 'name' => 'Dipaculao', 'province_id' => 36],
			['id' => 291, 'name' => 'Maria Aurora', 'province_id' => 36],
			['id' => 292, 'name' => 'San Luis', 'province_id' => 36],
			['id' => 293, 'name' => 'Balanga', 'province_id' => 37],
			['id' => 294, 'name' => 'Abucay', 'province_id' => 37],
			['id' => 295, 'name' => 'Bagac', 'province_id' => 37],
			['id' => 296, 'name' => 'Dinalupihan', 'province_id' => 37],
			['id' => 297, 'name' => 'Hermosa', 'province_id' => 37],
			['id' => 298, 'name' => 'Limay', 'province_id' => 37],
			['id' => 299, 'name' => 'Mariveles', 'province_id' => 37],
			['id' => 300, 'name' => 'Morong', 'province_id' => 37],
			['id' => 301, 'name' => 'Orani', 'province_id' => 37],
			['id' => 302, 'name' => 'Orion', 'province_id' => 37],
			['id' => 303, 'name' => 'Pilar', 'province_id' => 37],
			['id' => 304, 'name' => 'Samal', 'province_id' => 37],
			['id' => 305, 'name' => 'Angat', 'province_id' => 38],
			['id' => 306, 'name' => 'Balagtas (Bigaa)', 'province_id' => 38],
			['id' => 307, 'name' => 'Baliuag', 'province_id' => 38],
			['id' => 308, 'name' => 'Bocaue', 'province_id' => 38],
			['id' => 309, 'name' => 'Bulacan', 'province_id' => 38],
			['id' => 310, 'name' => 'Bustos', 'province_id' => 38],
			['id' => 311, 'name' => 'Calumpit', 'province_id' => 38],
			['id' => 312, 'name' => 'Doña Remedios Trinidad', 'province_id' => 38],
			['id' => 313, 'name' => 'Guiguinto', 'province_id' => 38],
			['id' => 314, 'name' => 'Hagonoy', 'province_id' => 38],
			['id' => 315, 'name' => 'Malolos City', 'province_id' => 38],
			['id' => 316, 'name' => 'Marilao', 'province_id' => 38],
			['id' => 317, 'name' => 'Meycauayan City', 'province_id' => 38],
			['id' => 318, 'name' => 'Norzagaray', 'province_id' => 38],
			['id' => 319, 'name' => 'Obando', 'province_id' => 38],
			['id' => 320, 'name' => 'Pandi', 'province_id' => 38],
			['id' => 321, 'name' => 'Paombong', 'province_id' => 38],
			['id' => 322, 'name' => 'Plaridel', 'province_id' => 38],
			['id' => 323, 'name' => 'Pulilan', 'province_id' => 38],
			['id' => 324, 'name' => 'San Ildefonso', 'province_id' => 38],
			['id' => 325, 'name' => 'San Jose del Monte', 'province_id' => 38],
			['id' => 326, 'name' => 'San Miguel', 'province_id' => 38],
			['id' => 327, 'name' => 'San Rafael', 'province_id' => 38],
			['id' => 328, 'name' => 'Cabanatuan City', 'province_id' => 39],
			['id' => 329, 'name' => 'Gapan City', 'province_id' => 39],
			['id' => 330, 'name' => 'Palayan City', 'province_id' => 39],
			['id' => 331, 'name' => 'San Jose City', 'province_id' => 39],
			['id' => 332, 'name' => 'Muñoz', 'province_id' => 39],
			['id' => 333, 'name' => 'Aliaga', 'province_id' => 39],
			['id' => 334, 'name' => 'Bongabon', 'province_id' => 39],
			['id' => 335, 'name' => 'Cabiao', 'province_id' => 39],
			['id' => 336, 'name' => 'Carranglan', 'province_id' => 39],
			['id' => 337, 'name' => 'Cuyapo', 'province_id' => 39],
			['id' => 338, 'name' => 'Gabaldon', 'province_id' => 39],
			['id' => 339, 'name' => 'Gen. Mamerto Natividad', 'province_id' => 39],
			['id' => 340, 'name' => 'Guimba', 'province_id' => 39],
			['id' => 341, 'name' => 'General Tinio', 'province_id' => 39],
			['id' => 342, 'name' => 'JaÃƒÂ©n', 'province_id' => 39],
			['id' => 343, 'name' => 'Laur', 'province_id' => 39],
			['id' => 344, 'name' => 'Licab', 'province_id' => 39],
			['id' => 345, 'name' => 'Llanera', 'province_id' => 39],
			['id' => 346, 'name' => 'Lupao', 'province_id' => 39],
			['id' => 347, 'name' => 'Nampicuan', 'province_id' => 39],
			['id' => 348, 'name' => 'Pantabangan', 'province_id' => 39],
			['id' => 349, 'name' => 'Peñaranda', 'province_id' => 39],
			['id' => 350, 'name' => 'Quezon', 'province_id' => 39],
			['id' => 351, 'name' => 'Rizal', 'province_id' => 39],
			['id' => 352, 'name' => 'San Antonio', 'province_id' => 39],
			['id' => 353, 'name' => 'San Isidro', 'province_id' => 39],
			['id' => 354, 'name' => 'San Leonardo', 'province_id' => 39],
			['id' => 355, 'name' => 'Santa Rosa', 'province_id' => 39],
			['id' => 356, 'name' => 'Santo Domingo', 'province_id' => 39],
			['id' => 357, 'name' => 'Talavera', 'province_id' => 39],
			['id' => 358, 'name' => 'Talugtug', 'province_id' => 39],
			['id' => 359, 'name' => 'Zaragoza', 'province_id' => 39],
			['id' => 360, 'name' => 'Olongapo', 'province_id' => 40],
			['id' => 361, 'name' => 'Angeles City', 'province_id' => 41],
			['id' => 362, 'name' => 'San Fernando', 'province_id' => 41],
			['id' => 363, 'name' => 'Mabalacat', 'province_id' => 41],
			['id' => 364, 'name' => 'Apalit', 'province_id' => 41],
			['id' => 365, 'name' => 'Arayat', 'province_id' => 41],
			['id' => 366, 'name' => 'Bacolor', 'province_id' => 41],
			['id' => 367, 'name' => 'Candaba', 'province_id' => 41],
			['id' => 368, 'name' => 'Floridablanca', 'province_id' => 41],
			['id' => 369, 'name' => 'Guagua', 'province_id' => 41],
			['id' => 370, 'name' => 'Lubao', 'province_id' => 41],
			['id' => 371, 'name' => 'Macabebe', 'province_id' => 41],
			['id' => 372, 'name' => 'Magalang', 'province_id' => 41],
			['id' => 373, 'name' => 'Masantol', 'province_id' => 41],
			['id' => 374, 'name' => 'Mexico', 'province_id' => 41],
			['id' => 375, 'name' => 'Minalin', 'province_id' => 41],
			['id' => 376, 'name' => 'Porac', 'province_id' => 41],
			['id' => 377, 'name' => 'San Luis', 'province_id' => 41],
			['id' => 378, 'name' => 'San Simon', 'province_id' => 41],
			['id' => 379, 'name' => 'Santa Ana', 'province_id' => 41],
			['id' => 380, 'name' => 'Santa Rita', 'province_id' => 41],
			['id' => 381, 'name' => 'Santo Tomas', 'province_id' => 41],
			['id' => 382, 'name' => 'Sasmuan', 'province_id' => 41],
			['id' => 383, 'name' => 'Tarlac City', 'province_id' => 42],
			['id' => 384, 'name' => 'Concepcion', 'province_id' => 42],
			['id' => 385, 'name' => 'Capas', 'province_id' => 42],
			['id' => 386, 'name' => 'Paniqui', 'province_id' => 42],
			['id' => 387, 'name' => 'Gerona', 'province_id' => 42],
			['id' => 388, 'name' => 'Camiling', 'province_id' => 42],
			['id' => 389, 'name' => 'Bamban', 'province_id' => 42],
			['id' => 390, 'name' => 'La Paz', 'province_id' => 42],
			['id' => 391, 'name' => 'Victoria', 'province_id' => 42],
			['id' => 392, 'name' => 'Moncada', 'province_id' => 42],
			['id' => 393, 'name' => 'Santa Ignacia', 'province_id' => 42],
			['id' => 394, 'name' => 'San Jose', 'province_id' => 42],
			['id' => 395, 'name' => 'Mayantoc', 'province_id' => 42],
			['id' => 396, 'name' => 'San Manuel', 'province_id' => 42],
			['id' => 397, 'name' => 'Pura', 'province_id' => 42],
			['id' => 398, 'name' => 'Ramos', 'province_id' => 42],
			['id' => 399, 'name' => 'San Clemente', 'province_id' => 42],
			['id' => 400, 'name' => 'Anao', 'province_id' => 42],
			['id' => 401, 'name' => 'San Luis', 'province_id' => 42],
			['id' => 402, 'name' => 'San Simon', 'province_id' => 42],
			['id' => 403, 'name' => 'Santa Ana', 'province_id' => 42],
			['id' => 404, 'name' => 'Santa Rita', 'province_id' => 42],
			['id' => 405, 'name' => 'Santo Tomas', 'province_id' => 42],
			['id' => 406, 'name' => 'Sasmuan', 'province_id' => 42],
			['id' => 407, 'name' => 'Subic', 'province_id' => 43],
			['id' => 408, 'name' => 'Castillejos', 'province_id' => 43],
			['id' => 409, 'name' => 'San Marcelino', 'province_id' => 43],
			['id' => 410, 'name' => 'San Antonio', 'province_id' => 43],
			['id' => 411, 'name' => 'San Narciso', 'province_id' => 43],
			['id' => 412, 'name' => 'San Felipe', 'province_id' => 43],
			['id' => 413, 'name' => 'Cabangan', 'province_id' => 43],
			['id' => 414, 'name' => 'Botolan', 'province_id' => 43],
			['id' => 415, 'name' => 'Iba', 'province_id' => 43],
			['id' => 416, 'name' => 'Palauig', 'province_id' => 43],
			['id' => 417, 'name' => 'Masinloc', 'province_id' => 43],
			['id' => 418, 'name' => 'Candelaria', 'province_id' => 43],
			['id' => 419, 'name' => 'Santa Cruz', 'province_id' => 43],
			['id' => 420, 'name' => 'Batangas City', 'province_id' => 44],
			['id' => 421, 'name' => 'Lipa City', 'province_id' => 44],
			['id' => 422, 'name' => 'Tanauan City', 'province_id' => 44],
			['id' => 423, 'name' => 'Agoncillo', 'province_id' => 44],
			['id' => 424, 'name' => 'Alitagtag', 'province_id' => 44],
			['id' => 425, 'name' => 'Balayan', 'province_id' => 44],
			['id' => 426, 'name' => 'Balete', 'province_id' => 44],
			['id' => 427, 'name' => 'Bauan', 'province_id' => 44],
			['id' => 428, 'name' => 'Calaca', 'province_id' => 44],
			['id' => 429, 'name' => 'Calatagan', 'province_id' => 44],
			['id' => 430, 'name' => 'Cuenca', 'province_id' => 44],
			['id' => 431, 'name' => 'Ibaan', 'province_id' => 44],
			['id' => 432, 'name' => 'Laurel', 'province_id' => 44],
			['id' => 433, 'name' => 'Lemery', 'province_id' => 44],
			['id' => 434, 'name' => 'Lian', 'province_id' => 44],
			['id' => 435, 'name' => 'Lobo', 'province_id' => 44],
			['id' => 436, 'name' => 'Mabini', 'province_id' => 44],
			['id' => 437, 'name' => 'Malvar', 'province_id' => 44],
			['id' => 438, 'name' => 'Mataasnakahoy', 'province_id' => 44],
			['id' => 439, 'name' => 'Nasugbu', 'province_id' => 44],
			['id' => 440, 'name' => 'Padre Garcia', 'province_id' => 44],
			['id' => 441, 'name' => 'Rosario', 'province_id' => 44],
			['id' => 442, 'name' => 'San Jose', 'province_id' => 44],
			['id' => 443, 'name' => 'San Juan', 'province_id' => 44],
			['id' => 444, 'name' => 'San Luis', 'province_id' => 44],
			['id' => 445, 'name' => 'San Nicolas', 'province_id' => 44],
			['id' => 446, 'name' => 'San Pascual', 'province_id' => 44],
			['id' => 447, 'name' => 'Santa Teresita', 'province_id' => 44],
			['id' => 448, 'name' => 'Santo Tomas', 'province_id' => 44],
			['id' => 449, 'name' => 'Taal', 'province_id' => 44],
			['id' => 450, 'name' => 'Talisay', 'province_id' => 44],
			['id' => 451, 'name' => 'Taysan', 'province_id' => 44],
			['id' => 452, 'name' => 'Tingloy', 'province_id' => 44],
			['id' => 453, 'name' => 'Bacoor', 'province_id' => 45],
			['id' => 454, 'name' => 'Cavite City', 'province_id' => 45],
			['id' => 455, 'name' => 'Dasmariñas', 'province_id' => 45],
			['id' => 456, 'name' => 'Imus', 'province_id' => 45],
			['id' => 457, 'name' => 'Tagaytay', 'province_id' => 45],
			['id' => 458, 'name' => 'Trece Martires', 'province_id' => 45],
			['id' => 459, 'name' => 'Alfonso', 'province_id' => 45],
			['id' => 460, 'name' => 'Amadeo', 'province_id' => 45],
			['id' => 461, 'name' => 'Carmona', 'province_id' => 45],
			['id' => 462, 'name' => 'General Emilio Aguinaldo', 'province_id' => 45],
			['id' => 463, 'name' => 'General Mariano Alvarez', 'province_id' => 45],
			['id' => 464, 'name' => 'General Trias', 'province_id' => 45],
			['id' => 465, 'name' => 'Indang', 'province_id' => 45],
			['id' => 466, 'name' => 'Kawit', 'province_id' => 45],
			['id' => 467, 'name' => 'Magallanes', 'province_id' => 45],
			['id' => 468, 'name' => 'Maragondon', 'province_id' => 45],
			['id' => 469, 'name' => 'Mendez', 'province_id' => 45],
			['id' => 470, 'name' => 'Naic', 'province_id' => 45],
			['id' => 471, 'name' => 'Noveleta', 'province_id' => 45],
			['id' => 472, 'name' => 'Rosario', 'province_id' => 45],
			['id' => 473, 'name' => 'Silang', 'province_id' => 45],
			['id' => 474, 'name' => 'Tanza', 'province_id' => 45],
			['id' => 475, 'name' => 'Ternate', 'province_id' => 45],
			['id' => 476, 'name' => 'Biñan', 'province_id' => 46],
			['id' => 477, 'name' => 'Cabuyao', 'province_id' => 46],
			['id' => 478, 'name' => 'Calamba', 'province_id' => 46],
			['id' => 479, 'name' => 'San Pablo', 'province_id' => 46],
			['id' => 480, 'name' => 'San Pedro', 'province_id' => 46],
			['id' => 481, 'name' => 'Santa Rosa', 'province_id' => 46],
			['id' => 482, 'name' => 'Alaminos', 'province_id' => 46],
			['id' => 483, 'name' => 'Bay', 'province_id' => 46],
			['id' => 484, 'name' => 'Calauan', 'province_id' => 46],
			['id' => 485, 'name' => 'Cavinti', 'province_id' => 46],
			['id' => 486, 'name' => 'Famy', 'province_id' => 46],
			['id' => 487, 'name' => 'Kalayaan', 'province_id' => 46],
			['id' => 488, 'name' => 'Liliw', 'province_id' => 46],
			['id' => 489, 'name' => 'Los Baños', 'province_id' => 46],
			['id' => 490, 'name' => 'Luisiana', 'province_id' => 46],
			['id' => 491, 'name' => 'Lumban', 'province_id' => 46],
			['id' => 492, 'name' => 'Mabitac', 'province_id' => 46],
			['id' => 493, 'name' => 'Magdalena', 'province_id' => 46],
			['id' => 494, 'name' => 'Majayjay', 'province_id' => 46],
			['id' => 495, 'name' => 'Nagcarlan', 'province_id' => 46],
			['id' => 496, 'name' => 'Paete', 'province_id' => 46],
			['id' => 497, 'name' => 'Pagsanjan', 'province_id' => 46],
			['id' => 498, 'name' => 'Pakil', 'province_id' => 46],
			['id' => 499, 'name' => 'Pangil', 'province_id' => 46],
			['id' => 500, 'name' => 'Pila', 'province_id' => 46],
			['id' => 501, 'name' => 'Rizal', 'province_id' => 46],
			['id' => 502, 'name' => 'Santa Cruz', 'province_id' => 46],
			['id' => 503, 'name' => 'Santa Maria', 'province_id' => 46],
			['id' => 504, 'name' => 'Siniloan', 'province_id' => 46],
			['id' => 505, 'name' => 'Victoria', 'province_id' => 46],
			['id' => 506, 'name' => 'Lucena', 'province_id' => 47],
			['id' => 507, 'name' => 'Angono', 'province_id' => 49],
			['id' => 508, 'name' => 'Antipolo', 'province_id' => 49],
			['id' => 509, 'name' => 'Baras', 'province_id' => 49],
			['id' => 510, 'name' => 'Binangonan', 'province_id' => 49],
			['id' => 511, 'name' => 'Cainta', 'province_id' => 49],
			['id' => 512, 'name' => 'Cardona', 'province_id' => 49],
			['id' => 513, 'name' => 'Jalajala', 'province_id' => 49],
			['id' => 514, 'name' => 'Morong', 'province_id' => 49],
			['id' => 515, 'name' => 'Pililla', 'province_id' => 49],
			['id' => 516, 'name' => 'Rodriguez', 'province_id' => 49],
			['id' => 517, 'name' => 'San Mateo', 'province_id' => 49],
			['id' => 518, 'name' => 'Tanay', 'province_id' => 49],
			['id' => 519, 'name' => 'Taytay', 'province_id' => 49],
			['id' => 520, 'name' => 'Teresa', 'province_id' => 49],
			['id' => 521, 'name' => 'Burdeos', 'province_id' => 48],
			['id' => 522, 'name' => 'General Nakar', 'province_id' => 48],
			['id' => 523, 'name' => 'Infanta', 'province_id' => 48],
			['id' => 524, 'name' => 'Jomalig', 'province_id' => 48],
			['id' => 525, 'name' => 'Lucban', 'province_id' => 48],
			['id' => 526, 'name' => 'Mauban', 'province_id' => 48],
			['id' => 527, 'name' => 'Pagbilao', 'province_id' => 48],
			['id' => 528, 'name' => 'Panukulan', 'province_id' => 48],
			['id' => 529, 'name' => 'Patnanungan', 'province_id' => 48],
			['id' => 530, 'name' => 'Polillo', 'province_id' => 48],
			['id' => 531, 'name' => 'Real', 'province_id' => 48],
			['id' => 532, 'name' => 'Sampaloc', 'province_id' => 48],
			['id' => 533, 'name' => 'Tayabas City', 'province_id' => 48],
			['id' => 534, 'name' => 'Candelaria', 'province_id' => 48],
			['id' => 535, 'name' => 'Dolores', 'province_id' => 48],
			['id' => 536, 'name' => 'Lucena City', 'province_id' => 48],
			['id' => 537, 'name' => 'San Antonio', 'province_id' => 48],
			['id' => 538, 'name' => 'Sariaya', 'province_id' => 48],
			['id' => 539, 'name' => 'Tiaong', 'province_id' => 48],
			['id' => 540, 'name' => 'Agdangan', 'province_id' => 48],
			['id' => 541, 'name' => 'Buenavista', 'province_id' => 48],
			['id' => 542, 'name' => 'Catanauan', 'province_id' => 48],
			['id' => 543, 'name' => 'General Luna', 'province_id' => 48],
			['id' => 544, 'name' => 'Macalelon', 'province_id' => 48],
			['id' => 545, 'name' => 'Mulanay', 'province_id' => 48],
			['id' => 546, 'name' => 'Padre Burgos', 'province_id' => 48],
			['id' => 547, 'name' => 'Pitogo', 'province_id' => 48],
			['id' => 548, 'name' => 'San Andres', 'province_id' => 48],
			['id' => 549, 'name' => 'San Francisco', 'province_id' => 48],
			['id' => 550, 'name' => 'San Narciso', 'province_id' => 48],
			['id' => 551, 'name' => 'Unisan', 'province_id' => 48],
			['id' => 552, 'name' => 'Alabat', 'province_id' => 48],
			['id' => 553, 'name' => 'Atimonan', 'province_id' => 48],
			['id' => 554, 'name' => 'Calauag', 'province_id' => 48],
			['id' => 555, 'name' => 'Guinayangan', 'province_id' => 48],
			['id' => 556, 'name' => 'Gumaca', 'province_id' => 48],
			['id' => 557, 'name' => 'Lopez', 'province_id' => 48],
			['id' => 558, 'name' => 'Perez', 'province_id' => 48],
			['id' => 559, 'name' => 'Plaridel', 'province_id' => 48],
			['id' => 560, 'name' => 'Quezon', 'province_id' => 48],
			['id' => 561, 'name' => 'Tagkawayan', 'province_id' => 48],
			['id' => 562, 'name' => 'Alcantara', 'province_id' => 55],
			['id' => 563, 'name' => 'Banton', 'province_id' => 55],
			['id' => 564, 'name' => 'Cajidiocan', 'province_id' => 55],
			['id' => 565, 'name' => 'Calatrava', 'province_id' => 55],
			['id' => 566, 'name' => 'Concepcion', 'province_id' => 55],
			['id' => 567, 'name' => 'Corcuera', 'province_id' => 55],
			['id' => 568, 'name' => 'Ferrol', 'province_id' => 55],
			['id' => 569, 'name' => 'Looc', 'province_id' => 55],
			['id' => 570, 'name' => 'Magdiwang', 'province_id' => 55],
			['id' => 571, 'name' => 'Odiongan', 'province_id' => 55],
			['id' => 572, 'name' => 'Romblon', 'province_id' => 55],
			['id' => 573, 'name' => 'San Agustin', 'province_id' => 55],
			['id' => 574, 'name' => 'San Andres', 'province_id' => 55],
			['id' => 575, 'name' => 'San Fernando', 'province_id' => 55],
			['id' => 576, 'name' => 'San Jose', 'province_id' => 55],
			['id' => 577, 'name' => 'Santa Fe', 'province_id' => 55],
			['id' => 578, 'name' => 'Santa Maria', 'province_id' => 55],
			['id' => 579, 'name' => 'Boac', 'province_id' => 50],
			['id' => 580, 'name' => 'Buenavista', 'province_id' => 50],
			['id' => 581, 'name' => 'Gasan', 'province_id' => 50],
			['id' => 582, 'name' => 'Mogpog', 'province_id' => 50],
			['id' => 583, 'name' => 'Santa Cruz', 'province_id' => 50],
			['id' => 584, 'name' => 'Torrijos', 'province_id' => 50],
			['id' => 585, 'name' => 'Abra de Ilog', 'province_id' => 51],
			['id' => 586, 'name' => 'Calintaan', 'province_id' => 51],
			['id' => 587, 'name' => 'Looc', 'province_id' => 51],
			['id' => 588, 'name' => 'Lubang', 'province_id' => 51],
			['id' => 589, 'name' => 'Magsaysay', 'province_id' => 51],
			['id' => 590, 'name' => 'Mamburao', 'province_id' => 51],
			['id' => 591, 'name' => 'Paluan', 'province_id' => 51],
			['id' => 592, 'name' => 'Rizal', 'province_id' => 51],
			['id' => 593, 'name' => 'Sablayan', 'province_id' => 51],
			['id' => 594, 'name' => 'San Jose', 'province_id' => 51],
			['id' => 595, 'name' => 'Santa Cruz', 'province_id' => 51],
			['id' => 596, 'name' => 'Calapan City', 'province_id' => 52],
			['id' => 597, 'name' => 'Baco', 'province_id' => 52],
			['id' => 598, 'name' => 'Bansud', 'province_id' => 52],
			['id' => 599, 'name' => 'Bongabong', 'province_id' => 52],
			['id' => 600, 'name' => 'Bulalacao', 'province_id' => 52],
			['id' => 601, 'name' => 'Gloria', 'province_id' => 52],
			['id' => 602, 'name' => 'Mansalay', 'province_id' => 52],
			['id' => 603, 'name' => 'Naujan', 'province_id' => 52],
			['id' => 604, 'name' => 'Pinamalayan', 'province_id' => 52],
			['id' => 605, 'name' => 'Pola', 'province_id' => 52],
			['id' => 606, 'name' => 'Puerto Galera', 'province_id' => 52],
			['id' => 607, 'name' => 'Roxas', 'province_id' => 52],
			['id' => 608, 'name' => 'San Teodoro', 'province_id' => 52],
			['id' => 609, 'name' => 'Socorro', 'province_id' => 52],
			['id' => 610, 'name' => 'Victoria', 'province_id' => 52],
			['id' => 611, 'name' => 'Aborlan', 'province_id' => 53],
			['id' => 612, 'name' => 'Bataraza', 'province_id' => 53],
			['id' => 613, 'name' => 'Dumaran', 'province_id' => 53],
			['id' => 614, 'name' => 'El Nido (Bacuit)', 'province_id' => 53],
			['id' => 615, 'name' => 'Narra', 'province_id' => 53],
			['id' => 616, 'name' => 'Quezon', 'province_id' => 53],
			['id' => 617, 'name' => 'Rizal (Marcos)', 'province_id' => 53],
			['id' => 618, 'name' => 'Roxas', 'province_id' => 53],
			['id' => 619, 'name' => 'San Vicente', 'province_id' => 53],
			['id' => 620, 'name' => 'Sofronio Española', 'province_id' => 53],
			['id' => 621, 'name' => 'Taytay', 'province_id' => 53],
			['id' => 622, 'name' => ' Puerto Princesa', 'province_id' => 54],
			['id' => 623, 'name' => 'Bacacay', 'province_id' => 56],
			['id' => 624, 'name' => 'Camalig', 'province_id' => 56],
			['id' => 625, 'name' => 'Daraga', 'province_id' => 56],
			['id' => 626, 'name' => 'Guinobatan', 'province_id' => 56],
			['id' => 627, 'name' => 'Jovellar', 'province_id' => 56],
			['id' => 628, 'name' => 'Legazpi City', 'province_id' => 56],
			['id' => 629, 'name' => 'Libon', 'province_id' => 56],
			['id' => 630, 'name' => 'Ligao City', 'province_id' => 56],
			['id' => 631, 'name' => 'Malilipot', 'province_id' => 56],
			['id' => 632, 'name' => 'Malinao', 'province_id' => 56],
			['id' => 633, 'name' => 'Manito', 'province_id' => 56],
			['id' => 634, 'name' => 'Oas', 'province_id' => 56],
			['id' => 635, 'name' => 'Pio Duran', 'province_id' => 56],
			['id' => 636, 'name' => 'Polangui', 'province_id' => 56],
			['id' => 637, 'name' => 'Rapu-Rapu', 'province_id' => 56],
			['id' => 638, 'name' => 'Santo Domingo', 'province_id' => 56],
			['id' => 639, 'name' => 'Tabaco City', 'province_id' => 56],
			['id' => 640, 'name' => 'Tiwi', 'province_id' => 56],
			['id' => 641, 'name' => 'Basud', 'province_id' => 57],
			['id' => 642, 'name' => 'Capalonga', 'province_id' => 57],
			['id' => 643, 'name' => 'Daet (capital town)', 'province_id' => 57],
			['id' => 644, 'name' => 'Jose Panganiban', 'province_id' => 57],
			['id' => 645, 'name' => 'Labo', 'province_id' => 57],
			['id' => 646, 'name' => 'Mercedes', 'province_id' => 57],
			['id' => 647, 'name' => 'Paracale', 'province_id' => 57],
			['id' => 648, 'name' => 'San Lorenzo Ruiz', 'province_id' => 57],
			['id' => 649, 'name' => 'San Vicente', 'province_id' => 57],
			['id' => 650, 'name' => 'Santa Elena', 'province_id' => 57],
			['id' => 651, 'name' => 'Talisay', 'province_id' => 57],
			['id' => 652, 'name' => 'Vinzons', 'province_id' => 57],
			['id' => 653, 'name' => 'Baao', 'province_id' => 58],
			['id' => 654, 'name' => 'Balatan', 'province_id' => 58],
			['id' => 655, 'name' => 'Bato', 'province_id' => 58],
			['id' => 656, 'name' => 'Bombon', 'province_id' => 58],
			['id' => 657, 'name' => 'Buhi', 'province_id' => 58],
			['id' => 658, 'name' => 'Bula', 'province_id' => 58],
			['id' => 659, 'name' => 'Cabusao', 'province_id' => 58],
			['id' => 660, 'name' => 'Calabanga', 'province_id' => 58],
			['id' => 661, 'name' => 'Camaligan', 'province_id' => 58],
			['id' => 662, 'name' => 'Canaman', 'province_id' => 58],
			['id' => 663, 'name' => 'Caramoan', 'province_id' => 58],
			['id' => 664, 'name' => 'Del Gallego', 'province_id' => 58],
			['id' => 665, 'name' => 'Gainza', 'province_id' => 58],
			['id' => 666, 'name' => 'Garchitorena', 'province_id' => 58],
			['id' => 667, 'name' => 'Goa', 'province_id' => 58],
			['id' => 668, 'name' => 'Iriga City', 'province_id' => 58],
			['id' => 669, 'name' => 'Lagonoy', 'province_id' => 58],
			['id' => 670, 'name' => 'Libmanan', 'province_id' => 58],
			['id' => 671, 'name' => 'Lupi', 'province_id' => 58],
			['id' => 672, 'name' => 'Magarao', 'province_id' => 58],
			['id' => 673, 'name' => 'Milaor', 'province_id' => 58],
			['id' => 674, 'name' => 'Minalabac', 'province_id' => 58],
			['id' => 675, 'name' => 'Nabua', 'province_id' => 58],
			['id' => 676, 'name' => 'Naga City', 'province_id' => 58],
			['id' => 677, 'name' => 'Ocampo', 'province_id' => 58],
			['id' => 678, 'name' => 'Pamplona', 'province_id' => 58],
			['id' => 679, 'name' => 'Pasacao', 'province_id' => 58],
			['id' => 680, 'name' => 'Pili', 'province_id' => 58],
			['id' => 681, 'name' => 'Presentacion', 'province_id' => 58],
			['id' => 682, 'name' => 'Ragay', 'province_id' => 58],
			['id' => 683, 'name' => 'Sagñay', 'province_id' => 58],
			['id' => 684, 'name' => 'San Fernando', 'province_id' => 58],
			['id' => 685, 'name' => 'San Jose', 'province_id' => 58],
			['id' => 686, 'name' => 'Sipocot', 'province_id' => 58],
			['id' => 687, 'name' => 'Siruma', 'province_id' => 58],
			['id' => 688, 'name' => 'Tigaon', 'province_id' => 58],
			['id' => 689, 'name' => 'Tinambac', 'province_id' => 58],
			['id' => 690, 'name' => 'Bagamanoc', 'province_id' => 59],
			['id' => 691, 'name' => 'Baras', 'province_id' => 59],
			['id' => 692, 'name' => 'Bato', 'province_id' => 59],
			['id' => 693, 'name' => 'Caramoran', 'province_id' => 59],
			['id' => 694, 'name' => 'Gigmoto', 'province_id' => 59],
			['id' => 695, 'name' => 'Pandan', 'province_id' => 59],
			['id' => 696, 'name' => 'Panganiban (Payo)', 'province_id' => 59],
			['id' => 697, 'name' => 'San Andres (Calolbon)', 'province_id' => 59],
			['id' => 698, 'name' => 'San Miguel', 'province_id' => 59],
			['id' => 699, 'name' => 'Viga', 'province_id' => 59],
			['id' => 700, 'name' => 'Virac (capital)', 'province_id' => 59],
			['id' => 701, 'name' => 'Aroroy', 'province_id' => 60],
			['id' => 702, 'name' => 'Baleno', 'province_id' => 60],
			['id' => 703, 'name' => 'Balud', 'province_id' => 60],
			['id' => 704, 'name' => 'Batuan', 'province_id' => 60],
			['id' => 705, 'name' => 'Cataingan', 'province_id' => 60],
			['id' => 706, 'name' => 'Cawayan', 'province_id' => 60],
			['id' => 707, 'name' => 'Claveria', 'province_id' => 60],
			['id' => 708, 'name' => 'Dimasalang', 'province_id' => 60],
			['id' => 709, 'name' => 'Esperanza', 'province_id' => 60],
			['id' => 710, 'name' => 'Mandaon', 'province_id' => 60],
			['id' => 711, 'name' => 'Masbate City', 'province_id' => 60],
			['id' => 712, 'name' => 'Milagros', 'province_id' => 60],
			['id' => 713, 'name' => 'Mobo', 'province_id' => 60],
			['id' => 714, 'name' => 'Monreal', 'province_id' => 60],
			['id' => 715, 'name' => 'Palanas', 'province_id' => 60],
			['id' => 716, 'name' => 'Pio V. Corpuz', 'province_id' => 60],
			['id' => 717, 'name' => 'Placer', 'province_id' => 60],
			['id' => 718, 'name' => 'San Fernando', 'province_id' => 60],
			['id' => 719, 'name' => 'San Jacinto', 'province_id' => 60],
			['id' => 720, 'name' => 'San Pascual', 'province_id' => 60],
			['id' => 721, 'name' => 'Uson', 'province_id' => 60],
			['id' => 722, 'name' => ' Naga city', 'province_id' => 61],
			['id' => 723, 'name' => 'Barcelona', 'province_id' => 62],
			['id' => 724, 'name' => 'Bulan', 'province_id' => 62],
			['id' => 725, 'name' => 'Bulusan', 'province_id' => 62],
			['id' => 726, 'name' => 'Casiguran', 'province_id' => 62],
			['id' => 727, 'name' => 'Castilla', 'province_id' => 62],
			['id' => 728, 'name' => 'Donsol', 'province_id' => 62],
			['id' => 729, 'name' => 'Gubat', 'province_id' => 62],
			['id' => 730, 'name' => 'Irosin', 'province_id' => 62],
			['id' => 731, 'name' => 'Juban', 'province_id' => 62],
			['id' => 732, 'name' => 'Magallanes', 'province_id' => 62],
			['id' => 733, 'name' => 'Matnog', 'province_id' => 62],
			['id' => 734, 'name' => 'Pilar', 'province_id' => 62],
			['id' => 735, 'name' => 'Prieto Diaz', 'province_id' => 62],
			['id' => 736, 'name' => 'Santa Magdalena', 'province_id' => 62],
			['id' => 737, 'name' => 'Sorsogon City', 'province_id' => 62],
			['id' => 738, 'name' => 'Altavas', 'province_id' => 63],
			['id' => 739, 'name' => 'Balete', 'province_id' => 63],
			['id' => 740, 'name' => 'Banga', 'province_id' => 63],
			['id' => 741, 'name' => 'Batan', 'province_id' => 63],
			['id' => 742, 'name' => 'Buruanga', 'province_id' => 63],
			['id' => 743, 'name' => 'Ibajay', 'province_id' => 63],
			['id' => 744, 'name' => 'Kalibo', 'province_id' => 63],
			['id' => 745, 'name' => 'Lezo', 'province_id' => 63],
			['id' => 746, 'name' => 'Libacao', 'province_id' => 63],
			['id' => 747, 'name' => 'Madalag', 'province_id' => 63],
			['id' => 748, 'name' => 'Makato', 'province_id' => 63],
			['id' => 749, 'name' => 'Malay', 'province_id' => 63],
			['id' => 750, 'name' => 'Malinao', 'province_id' => 63],
			['id' => 751, 'name' => 'Nabas', 'province_id' => 63],
			['id' => 752, 'name' => 'New Washington', 'province_id' => 63],
			['id' => 753, 'name' => 'Numancia', 'province_id' => 63],
			['id' => 754, 'name' => 'Tangalan', 'province_id' => 63],
			['id' => 755, 'name' => 'Anini-y', 'province_id' => 64],
			['id' => 756, 'name' => 'Barbaza', 'province_id' => 64],
			['id' => 757, 'name' => 'Belison', 'province_id' => 64],
			['id' => 758, 'name' => 'Bugasong', 'province_id' => 64],
			['id' => 759, 'name' => 'Caluya', 'province_id' => 64],
			['id' => 760, 'name' => 'Culasi', 'province_id' => 64],
			['id' => 761, 'name' => 'Hamtic', 'province_id' => 64],
			['id' => 762, 'name' => 'Laua-an', 'province_id' => 64],
			['id' => 763, 'name' => 'Libertad', 'province_id' => 64],
			['id' => 764, 'name' => 'Pandan', 'province_id' => 64],
			['id' => 765, 'name' => 'Patnongon', 'province_id' => 64],
			['id' => 766, 'name' => 'San Jose de Buenavista', 'province_id' => 64],
			['id' => 767, 'name' => 'San Remigio', 'province_id' => 64],
			['id' => 768, 'name' => 'Sebaste', 'province_id' => 64],
			['id' => 769, 'name' => 'Sibalom', 'province_id' => 64],
			['id' => 770, 'name' => 'Tibiao', 'province_id' => 64],
			['id' => 771, 'name' => 'Tobias Fornier', 'province_id' => 64],
			['id' => 772, 'name' => 'Valderrama', 'province_id' => 64],
			['id' => 773, 'name' => ' Bacolod City', 'province_id' => 65],
			['id' => 774, 'name' => 'Roxas City', 'province_id' => 66],
			['id' => 775, 'name' => 'Cuartero', 'province_id' => 66],
			['id' => 776, 'name' => 'Dao', 'province_id' => 66],
			['id' => 777, 'name' => 'Dumalag', 'province_id' => 66],
			['id' => 778, 'name' => 'Dumarao', 'province_id' => 66],
			['id' => 779, 'name' => 'Ivisan', 'province_id' => 66],
			['id' => 780, 'name' => 'Jamindan', 'province_id' => 66],
			['id' => 781, 'name' => 'Ma-ayon', 'province_id' => 66],
			['id' => 782, 'name' => 'Mambusao', 'province_id' => 66],
			['id' => 783, 'name' => 'Panay', 'province_id' => 66],
			['id' => 784, 'name' => 'Panitan', 'province_id' => 66],
			['id' => 785, 'name' => 'Pilar', 'province_id' => 66],
			['id' => 786, 'name' => 'Pontevedra', 'province_id' => 66],
			['id' => 787, 'name' => 'President Roxas', 'province_id' => 66],
			['id' => 788, 'name' => 'Sapian', 'province_id' => 66],
			['id' => 789, 'name' => 'Sigma', 'province_id' => 66],
			['id' => 790, 'name' => 'Tapaz', 'province_id' => 66],
			['id' => 791, 'name' => 'Buenavista', 'province_id' => 67],
			['id' => 792, 'name' => 'Jordan (capital)', 'province_id' => 67],
			['id' => 793, 'name' => 'Nueva Valencia', 'province_id' => 67],
			['id' => 794, 'name' => 'San Lorenzo', 'province_id' => 67],
			['id' => 795, 'name' => 'Sibunag', 'province_id' => 67],
			['id' => 796, 'name' => 'Ajuy', 'province_id' => 69],
			['id' => 797, 'name' => 'Alimodian', 'province_id' => 69],
			['id' => 798, 'name' => 'Anilao', 'province_id' => 69],
			['id' => 799, 'name' => 'Badiangan', 'province_id' => 69],
			['id' => 800, 'name' => 'Balasan', 'province_id' => 69],
			['id' => 801, 'name' => 'Banate', 'province_id' => 69],
			['id' => 802, 'name' => 'Barotac Nuevo', 'province_id' => 69],
			['id' => 803, 'name' => 'Barotac Viejo', 'province_id' => 69],
			['id' => 804, 'name' => 'Batad', 'province_id' => 69],
			['id' => 805, 'name' => 'Bingawan', 'province_id' => 69],
			['id' => 806, 'name' => 'Cabatuan', 'province_id' => 69],
			['id' => 807, 'name' => 'Calinog', 'province_id' => 69],
			['id' => 808, 'name' => 'Carles', 'province_id' => 69],
			['id' => 809, 'name' => 'Concepcion', 'province_id' => 69],
			['id' => 810, 'name' => 'Dingle', 'province_id' => 69],
			['id' => 811, 'name' => 'Dueñas', 'province_id' => 69],
			['id' => 812, 'name' => 'Dumangas', 'province_id' => 69],
			['id' => 813, 'name' => 'Estancia', 'province_id' => 69],
			['id' => 814, 'name' => 'Guimbal', 'province_id' => 69],
			['id' => 815, 'name' => 'Igbaras', 'province_id' => 69],
			['id' => 816, 'name' => 'Janiuay', 'province_id' => 69],
			['id' => 817, 'name' => 'Lambunao', 'province_id' => 69],
			['id' => 818, 'name' => 'Leganes', 'province_id' => 69],
			['id' => 819, 'name' => 'Lemery', 'province_id' => 69],
			['id' => 820, 'name' => 'Leon', 'province_id' => 69],
			['id' => 821, 'name' => 'Maasin', 'province_id' => 69],
			['id' => 822, 'name' => 'Miagao', 'province_id' => 69],
			['id' => 823, 'name' => 'Mina', 'province_id' => 69],
			['id' => 824, 'name' => 'New Lucena', 'province_id' => 69],
			['id' => 825, 'name' => 'Oton', 'province_id' => 69],
			['id' => 826, 'name' => 'Pavia', 'province_id' => 69],
			['id' => 827, 'name' => 'Pototan', 'province_id' => 69],
			['id' => 828, 'name' => 'San Dionisio', 'province_id' => 69],
			['id' => 829, 'name' => 'San Enrique', 'province_id' => 69],
			['id' => 830, 'name' => 'San Joaquin', 'province_id' => 69],
			['id' => 831, 'name' => 'San Miguel', 'province_id' => 69],
			['id' => 832, 'name' => 'San Rafael', 'province_id' => 69],
			['id' => 833, 'name' => 'Santa Barbara', 'province_id' => 69],
			['id' => 834, 'name' => 'Sara', 'province_id' => 69],
			['id' => 835, 'name' => 'Tigbauan', 'province_id' => 69],
			['id' => 836, 'name' => 'Tubungan', 'province_id' => 69],
			['id' => 837, 'name' => 'Zarraga', 'province_id' => 69],
			['id' => 838, 'name' => 'Iloilo', 'province_id' => 69],
			['id' => 839, 'name' => 'Passi City', 'province_id' => 69],
			['id' => 840, 'name' => 'Bacolod', 'province_id' => 70],
			['id' => 841, 'name' => 'Bago', 'province_id' => 70],
			['id' => 842, 'name' => 'Cadiz', 'province_id' => 70],
			['id' => 843, 'name' => 'Escalante', 'province_id' => 70],
			['id' => 844, 'name' => 'Himamaylan', 'province_id' => 70],
			['id' => 845, 'name' => 'Kabankalan', 'province_id' => 70],
			['id' => 846, 'name' => 'La Carlota', 'province_id' => 70],
			['id' => 847, 'name' => 'Sagay', 'province_id' => 70],
			['id' => 848, 'name' => 'San Carlos', 'province_id' => 70],
			['id' => 849, 'name' => 'Silay', 'province_id' => 70],
			['id' => 850, 'name' => 'Sipalay', 'province_id' => 70],
			['id' => 851, 'name' => 'Talisay', 'province_id' => 70],
			['id' => 852, 'name' => 'Victorias', 'province_id' => 70],
			['id' => 853, 'name' => 'Binalbagan', 'province_id' => 70],
			['id' => 854, 'name' => 'Calatrava', 'province_id' => 70],
			['id' => 855, 'name' => 'Candoni', 'province_id' => 70],
			['id' => 856, 'name' => 'Cauayan', 'province_id' => 70],
			['id' => 857, 'name' => 'Enrique B. Magalona (Saravia)', 'province_id' => 70],
			['id' => 858, 'name' => 'Hinigaran', 'province_id' => 70],
			['id' => 859, 'name' => 'Hinoba-an (Asia)', 'province_id' => 70],
			['id' => 860, 'name' => 'Ilog', 'province_id' => 70],
			['id' => 861, 'name' => 'Isabela', 'province_id' => 70],
			['id' => 862, 'name' => 'La Castellana', 'province_id' => 70],
			['id' => 863, 'name' => 'Manapla', 'province_id' => 70],
			['id' => 864, 'name' => 'Moises Padilla (Magallon)', 'province_id' => 70],
			['id' => 865, 'name' => 'Murcia', 'province_id' => 70],
			['id' => 866, 'name' => 'Pontevedra', 'province_id' => 70],
			['id' => 867, 'name' => 'Pulupandan', 'province_id' => 70],
			['id' => 868, 'name' => 'Salvador Benedicto', 'province_id' => 70],
			['id' => 869, 'name' => 'San Enrique', 'province_id' => 70],
			['id' => 870, 'name' => 'Toboso', 'province_id' => 70],
			['id' => 871, 'name' => 'Valladolid', 'province_id' => 70],
			['id' => 872, 'name' => 'Tagbilaran City', 'province_id' => 72],
			['id' => 873, 'name' => 'Alcantara', 'province_id' => 73],
			['id' => 874, 'name' => 'Alcoy', 'province_id' => 73],
			['id' => 875, 'name' => 'Alegria', 'province_id' => 73],
			['id' => 876, 'name' => 'Aloguinsan', 'province_id' => 73],
			['id' => 877, 'name' => 'Argao', 'province_id' => 73],
			['id' => 878, 'name' => 'Asturias', 'province_id' => 73],
			['id' => 879, 'name' => 'Badian', 'province_id' => 73],
			['id' => 880, 'name' => 'Balamban', 'province_id' => 73],
			['id' => 881, 'name' => 'Bantayan', 'province_id' => 73],
			['id' => 882, 'name' => 'Barili', 'province_id' => 73],
			['id' => 883, 'name' => 'Boljoon', 'province_id' => 73],
			['id' => 884, 'name' => 'Borbon', 'province_id' => 73],
			['id' => 885, 'name' => 'Carmen', 'province_id' => 73],
			['id' => 886, 'name' => 'Catmon', 'province_id' => 73],
			['id' => 887, 'name' => 'Compostela', 'province_id' => 73],
			['id' => 888, 'name' => 'Consolacion', 'province_id' => 73],
			['id' => 889, 'name' => 'Cordova', 'province_id' => 73],
			['id' => 890, 'name' => 'Daanbantayan', 'province_id' => 73],
			['id' => 891, 'name' => 'Dalaguete', 'province_id' => 73],
			['id' => 892, 'name' => 'Dumanjug', 'province_id' => 73],
			['id' => 893, 'name' => 'Ginatilan', 'province_id' => 73],
			['id' => 894, 'name' => 'Liloan', 'province_id' => 73],
			['id' => 895, 'name' => 'Madridejos', 'province_id' => 73],
			['id' => 896, 'name' => 'Malabuyoc', 'province_id' => 73],
			['id' => 897, 'name' => 'Medellin', 'province_id' => 73],
			['id' => 898, 'name' => 'Minglanilla', 'province_id' => 73],
			['id' => 899, 'name' => 'Moalboal', 'province_id' => 73],
			['id' => 900, 'name' => 'Oslob', 'province_id' => 73],
			['id' => 901, 'name' => 'Pilar', 'province_id' => 73],
			['id' => 902, 'name' => 'Pinamungahan', 'province_id' => 73],
			['id' => 903, 'name' => 'Poro', 'province_id' => 73],
			['id' => 904, 'name' => 'Ronda', 'province_id' => 73],
			['id' => 905, 'name' => 'Samboan', 'province_id' => 73],
			['id' => 906, 'name' => 'San Fernando', 'province_id' => 73],
			['id' => 907, 'name' => 'San Francisco', 'province_id' => 73],
			['id' => 908, 'name' => 'San Remigio', 'province_id' => 73],
			['id' => 909, 'name' => 'Santa Fe', 'province_id' => 73],
			['id' => 910, 'name' => 'Santander', 'province_id' => 73],
			['id' => 911, 'name' => 'Sibonga', 'province_id' => 73],
			['id' => 912, 'name' => 'Sogod', 'province_id' => 73],
			['id' => 913, 'name' => 'Tabogon', 'province_id' => 73],
			['id' => 914, 'name' => 'Tabuelan', 'province_id' => 73],
			['id' => 915, 'name' => 'Tuburan', 'province_id' => 73],
			['id' => 916, 'name' => 'Tudela', 'province_id' => 73],
			['id' => 917, 'name' => 'Lapu-lapu city', 'province_id' => 75],
			['id' => 918, 'name' => 'Mandaue city', 'province_id' => 76],
			['id' => 919, 'name' => 'Bais City', 'province_id' => 77],
			['id' => 920, 'name' => 'Bayawan City', 'province_id' => 77],
			['id' => 921, 'name' => 'Canlaon City', 'province_id' => 77],
			['id' => 922, 'name' => 'Dumaguete City', 'province_id' => 77],
			['id' => 923, 'name' => 'Guihulngan City', 'province_id' => 77],
			['id' => 924, 'name' => 'Tanjay City', 'province_id' => 77],
			['id' => 925, 'name' => 'Amlan', 'province_id' => 77],
			['id' => 926, 'name' => 'Ayungon', 'province_id' => 77],
			['id' => 927, 'name' => 'Bacong', 'province_id' => 77],
			['id' => 928, 'name' => 'Basay', 'province_id' => 77],
			['id' => 929, 'name' => 'Bindoy', 'province_id' => 77],
			['id' => 930, 'name' => 'Dauin', 'province_id' => 77],
			['id' => 931, 'name' => 'Jimalalud', 'province_id' => 77],
			['id' => 932, 'name' => 'La Libertad', 'province_id' => 77],
			['id' => 933, 'name' => 'Mabinay', 'province_id' => 77],
			['id' => 934, 'name' => 'Manjuyod', 'province_id' => 77],
			['id' => 935, 'name' => 'Pamplona', 'province_id' => 77],
			['id' => 936, 'name' => 'San Jose', 'province_id' => 77],
			['id' => 937, 'name' => 'Santa Catalina', 'province_id' => 77],
			['id' => 938, 'name' => 'Siaton', 'province_id' => 77],
			['id' => 939, 'name' => 'Sibulan', 'province_id' => 77],
			['id' => 940, 'name' => 'Tayasan', 'province_id' => 77],
			['id' => 941, 'name' => 'Valencia[14]', 'province_id' => 77],
			['id' => 942, 'name' => 'Vallehermoso', 'province_id' => 77],
			['id' => 943, 'name' => 'Zamboanguita', 'province_id' => 77],
			['id' => 944, 'name' => 'Enrique Villanueva', 'province_id' => 78],
			['id' => 945, 'name' => 'Larena', 'province_id' => 78],
			['id' => 946, 'name' => 'Lazi', 'province_id' => 78],
			['id' => 947, 'name' => 'Maria', 'province_id' => 78],
			['id' => 948, 'name' => 'San Juan Borling', 'province_id' => 78],
			['id' => 949, 'name' => 'Siquijor', 'province_id' => 78],
			['id' => 950, 'name' => 'Almeria', 'province_id' => 79],
			['id' => 951, 'name' => 'Biliran', 'province_id' => 79],
			['id' => 952, 'name' => 'Cabucgayan', 'province_id' => 79],
			['id' => 953, 'name' => 'Caibiran', 'province_id' => 79],
			['id' => 954, 'name' => 'Culaba', 'province_id' => 79],
			['id' => 955, 'name' => 'Kawayan', 'province_id' => 79],
			['id' => 956, 'name' => 'Maripipi', 'province_id' => 79],
			['id' => 957, 'name' => 'Naval', 'province_id' => 79],
			['id' => 958, 'name' => 'Borongan City', 'province_id' => 80],
			['id' => 959, 'name' => 'Arteche', 'province_id' => 80],
			['id' => 960, 'name' => 'Balangiga', 'province_id' => 80],
			['id' => 961, 'name' => 'Balangkayan', 'province_id' => 80],
			['id' => 962, 'name' => 'Can-avid', 'province_id' => 80],
			['id' => 963, 'name' => 'Dolores', 'province_id' => 80],
			['id' => 964, 'name' => 'General MacArthur', 'province_id' => 80],
			['id' => 965, 'name' => 'Giporlos', 'province_id' => 80],
			['id' => 966, 'name' => 'Guiuan', 'province_id' => 80],
			['id' => 967, 'name' => 'Hernani', 'province_id' => 80],
			['id' => 968, 'name' => 'Jipapad', 'province_id' => 80],
			['id' => 969, 'name' => 'Lawaan', 'province_id' => 80],
			['id' => 970, 'name' => 'Llorente', 'province_id' => 80],
			['id' => 971, 'name' => 'Maslog', 'province_id' => 80],
			['id' => 972, 'name' => 'Maydolong', 'province_id' => 80],
			['id' => 973, 'name' => 'Mercedes', 'province_id' => 80],
			['id' => 974, 'name' => 'Oras', 'province_id' => 80],
			['id' => 975, 'name' => 'Quinapondan', 'province_id' => 80],
			['id' => 976, 'name' => 'Salcedo', 'province_id' => 80],
			['id' => 977, 'name' => 'San Julian', 'province_id' => 80],
			['id' => 978, 'name' => 'San Policarpo', 'province_id' => 80],
			['id' => 979, 'name' => 'Sulat', 'province_id' => 80],
			['id' => 980, 'name' => 'Taft', 'province_id' => 80],
			['id' => 981, 'name' => 'Ormoc', 'province_id' => 81],
			['id' => 982, 'name' => 'Tacloban', 'province_id' => 81],
			['id' => 983, 'name' => 'Baybay', 'province_id' => 81],
			['id' => 984, 'name' => 'Abuyog', 'province_id' => 81],
			['id' => 985, 'name' => 'Alangalang', 'province_id' => 81],
			['id' => 986, 'name' => 'Albuera', 'province_id' => 81],
			['id' => 987, 'name' => 'Babatngon', 'province_id' => 81],
			['id' => 988, 'name' => 'Barugo', 'province_id' => 81],
			['id' => 989, 'name' => 'Bato', 'province_id' => 81],
			['id' => 990, 'name' => 'Burauen', 'province_id' => 81],
			['id' => 991, 'name' => 'Calubian', 'province_id' => 81],
			['id' => 992, 'name' => 'Capoocan', 'province_id' => 81],
			['id' => 993, 'name' => 'Carigara', 'province_id' => 81],
			['id' => 994, 'name' => 'Dagami', 'province_id' => 81],
			['id' => 995, 'name' => 'Dulag', 'province_id' => 81],
			['id' => 996, 'name' => 'Hilongos', 'province_id' => 81],
			['id' => 997, 'name' => 'Hindang', 'province_id' => 81],
			['id' => 998, 'name' => 'Inopacan', 'province_id' => 81],
			['id' => 999, 'name' => 'Isabel', 'province_id' => 81],
			['id' => 1000, 'name' => 'Jaro', 'province_id' => 81],
			['id' => 1001, 'name' => 'Javier', 'province_id' => 81],
			['id' => 1002, 'name' => 'Julita', 'province_id' => 81],
			['id' => 1003, 'name' => 'Kananga', 'province_id' => 81],
			['id' => 1004, 'name' => 'La Paz', 'province_id' => 81],
			['id' => 1005, 'name' => 'Leyte', 'province_id' => 81],
			['id' => 1006, 'name' => 'MacArthur', 'province_id' => 81],
			['id' => 1007, 'name' => 'Mahaplag', 'province_id' => 81],
			['id' => 1008, 'name' => 'Matag-ob', 'province_id' => 81],
			['id' => 1009, 'name' => 'Matalom', 'province_id' => 81],
			['id' => 1010, 'name' => 'Mayorga', 'province_id' => 81],
			['id' => 1011, 'name' => 'Merida', 'province_id' => 81],
			['id' => 1012, 'name' => 'Palo', 'province_id' => 81],
			['id' => 1013, 'name' => 'Palompon', 'province_id' => 81],
			['id' => 1014, 'name' => 'Pastrana', 'province_id' => 81],
			['id' => 1015, 'name' => 'San Isidro', 'province_id' => 81],
			['id' => 1016, 'name' => 'San Miguel', 'province_id' => 81],
			['id' => 1017, 'name' => 'Santa Fe', 'province_id' => 81],
			['id' => 1018, 'name' => 'Tabango', 'province_id' => 81],
			['id' => 1019, 'name' => 'Tabontabon', 'province_id' => 81],
			['id' => 1020, 'name' => 'Tanauan', 'province_id' => 81],
			['id' => 1021, 'name' => 'Tolosa', 'province_id' => 81],
			['id' => 1022, 'name' => 'Tunga', 'province_id' => 81],
			['id' => 1023, 'name' => 'Villaba', 'province_id' => 81],
			['id' => 1024, 'name' => 'Allen', 'province_id' => 82],
			['id' => 1025, 'name' => 'Biri', 'province_id' => 82],
			['id' => 1026, 'name' => 'Bobon', 'province_id' => 82],
			['id' => 1027, 'name' => 'Capul', 'province_id' => 82],
			['id' => 1028, 'name' => 'Catarman', 'province_id' => 82],
			['id' => 1029, 'name' => 'Catubig', 'province_id' => 82],
			['id' => 1030, 'name' => 'Gamay', 'province_id' => 82],
			['id' => 1031, 'name' => 'Laoang', 'province_id' => 82],
			['id' => 1032, 'name' => 'Lapinig', 'province_id' => 82],
			['id' => 1033, 'name' => 'Las Navas', 'province_id' => 82],
			['id' => 1034, 'name' => 'Lavezares', 'province_id' => 82],
			['id' => 1035, 'name' => 'Lope de Vega', 'province_id' => 82],
			['id' => 1036, 'name' => 'Mapanas', 'province_id' => 82],
			['id' => 1037, 'name' => 'Mondragon', 'province_id' => 82],
			['id' => 1038, 'name' => 'Palapag', 'province_id' => 82],
			['id' => 1039, 'name' => 'Pambujan', 'province_id' => 82],
			['id' => 1040, 'name' => 'Rosario', 'province_id' => 82],
			['id' => 1041, 'name' => 'San Antonio', 'province_id' => 82],
			['id' => 1042, 'name' => 'San Isidro', 'province_id' => 82],
			['id' => 1043, 'name' => 'San Jose', 'province_id' => 82],
			['id' => 1044, 'name' => 'San Roque', 'province_id' => 82],
			['id' => 1045, 'name' => 'San Vicente', 'province_id' => 82],
			['id' => 1046, 'name' => 'Silvino Lobos', 'province_id' => 82],
			['id' => 1047, 'name' => 'Victoria', 'province_id' => 82],
			['id' => 1048, 'name' => 'Ormoc city', 'province_id' => 83],
			['id' => 1049, 'name' => 'Anahawan', 'province_id' => 84],
			['id' => 1050, 'name' => 'Bontoc', 'province_id' => 84],
			['id' => 1051, 'name' => 'Hinunangan', 'province_id' => 84],
			['id' => 1052, 'name' => 'Hinundayan', 'province_id' => 84],
			['id' => 1053, 'name' => 'Libagon', 'province_id' => 84],
			['id' => 1054, 'name' => 'Liloan', 'province_id' => 84],
			['id' => 1055, 'name' => 'Limasawa', 'province_id' => 84],
			['id' => 1056, 'name' => 'Maasin City', 'province_id' => 84],
			['id' => 1057, 'name' => 'Macrohon', 'province_id' => 84],
			['id' => 1058, 'name' => 'Malitbog', 'province_id' => 84],
			['id' => 1059, 'name' => 'Padre Burgos', 'province_id' => 84],
			['id' => 1060, 'name' => 'Pintuyan', 'province_id' => 84],
			['id' => 1061, 'name' => 'Saint Bernard', 'province_id' => 84],
			['id' => 1062, 'name' => 'San Francisco', 'province_id' => 84],
			['id' => 1063, 'name' => 'San Juan', 'province_id' => 84],
			['id' => 1064, 'name' => 'San Ricardo', 'province_id' => 84],
			['id' => 1065, 'name' => 'Silago', 'province_id' => 84],
			['id' => 1066, 'name' => 'Sogod', 'province_id' => 84],
			['id' => 1067, 'name' => 'Tomas Oppus', 'province_id' => 84],
			['id' => 1068, 'name' => 'Tacloban', 'province_id' => 85],
			['id' => 1069, 'name' => 'Isabela', 'province_id' => 86],
			['id' => 1070, 'name' => 'Zamboanga City', 'province_id' => 87],
			['id' => 1071, 'name' => 'Dapitan City', 'province_id' => 88],
			['id' => 1072, 'name' => 'Dipolog City', 'province_id' => 88],
			['id' => 1073, 'name' => 'Leon B. Postigo (Bacungan)', 'province_id' => 88],
			['id' => 1074, 'name' => 'Baliguian', 'province_id' => 88],
			['id' => 1075, 'name' => 'Godod', 'province_id' => 88],
			['id' => 1076, 'name' => 'Gutalac', 'province_id' => 88],
			['id' => 1077, 'name' => 'Jose Dalman (Ponot)', 'province_id' => 88],
			['id' => 1078, 'name' => 'Kalawit', 'province_id' => 88],
			['id' => 1079, 'name' => 'Katipunan', 'province_id' => 88],
			['id' => 1080, 'name' => 'La Libertad', 'province_id' => 88],
			['id' => 1081, 'name' => 'Labason', 'province_id' => 88],
			['id' => 1082, 'name' => 'Liloy', 'province_id' => 88],
			['id' => 1083, 'name' => 'Manukan', 'province_id' => 88],
			['id' => 1084, 'name' => 'Mutia', 'province_id' => 88],
			['id' => 1085, 'name' => 'Piñan', 'province_id' => 88],
			['id' => 1086, 'name' => 'Polanco', 'province_id' => 88],
			['id' => 1087, 'name' => 'Pres. Manuel A. Roxas', 'province_id' => 88],
			['id' => 1088, 'name' => 'Rizal', 'province_id' => 88],
			['id' => 1089, 'name' => 'Salug', 'province_id' => 88],
			['id' => 1090, 'name' => 'Sergio Osmeña Sr.', 'province_id' => 88],
			['id' => 1091, 'name' => 'Siayan', 'province_id' => 88],
			['id' => 1092, 'name' => 'Sibuco', 'province_id' => 88],
			['id' => 1093, 'name' => 'Sibutad', 'province_id' => 88],
			['id' => 1094, 'name' => 'Sindangan', 'province_id' => 88],
			['id' => 1095, 'name' => 'Siocon', 'province_id' => 88],
			['id' => 1096, 'name' => 'Sirawai', 'province_id' => 88],
			['id' => 1097, 'name' => 'Tampilisan', 'province_id' => 88],
			['id' => 1098, 'name' => 'Pagadian City', 'province_id' => 89],
			['id' => 1099, 'name' => 'Aurora', 'province_id' => 89],
			['id' => 1100, 'name' => 'Bayog', 'province_id' => 89],
			['id' => 1101, 'name' => 'Dimataling', 'province_id' => 89],
			['id' => 1102, 'name' => 'Dinas', 'province_id' => 89],
			['id' => 1103, 'name' => 'Dumalinao', 'province_id' => 89],
			['id' => 1104, 'name' => 'Dumingag', 'province_id' => 89],
			['id' => 1105, 'name' => 'Guipos', 'province_id' => 89],
			['id' => 1106, 'name' => 'Josefina', 'province_id' => 89],
			['id' => 1107, 'name' => 'Kumalarang', 'province_id' => 89],
			['id' => 1108, 'name' => 'Labangan', 'province_id' => 89],
			['id' => 1109, 'name' => 'Lakewood', 'province_id' => 89],
			['id' => 1110, 'name' => 'Lapuyan', 'province_id' => 89],
			['id' => 1111, 'name' => 'Mahayag', 'province_id' => 89],
			['id' => 1112, 'name' => 'Margosatubig', 'province_id' => 89],
			['id' => 1113, 'name' => 'Midsalip', 'province_id' => 89],
			['id' => 1114, 'name' => 'Molave', 'province_id' => 89],
			['id' => 1115, 'name' => 'Pitogo', 'province_id' => 89],
			['id' => 1116, 'name' => 'Ramon Magsaysay (Liargo)', 'province_id' => 89],
			['id' => 1117, 'name' => 'San Miguel', 'province_id' => 89],
			['id' => 1118, 'name' => 'San Pablo', 'province_id' => 89],
			['id' => 1119, 'name' => 'Sominot (Don Mariano Marcos)', 'province_id' => 89],
			['id' => 1120, 'name' => 'Tabina', 'province_id' => 89],
			['id' => 1121, 'name' => 'Tambulig', 'province_id' => 89],
			['id' => 1122, 'name' => 'Tigbao', 'province_id' => 89],
			['id' => 1123, 'name' => 'Tukuran', 'province_id' => 89],
			['id' => 1124, 'name' => 'Vincenzo A. Sagun', 'province_id' => 89],
			['id' => 1125, 'name' => 'Alicia', 'province_id' => 90],
			['id' => 1126, 'name' => 'Buug', 'province_id' => 90],
			['id' => 1127, 'name' => 'Diplahan', 'province_id' => 90],
			['id' => 1128, 'name' => 'Imelda', 'province_id' => 90],
			['id' => 1129, 'name' => 'Ipil', 'province_id' => 90],
			['id' => 1130, 'name' => 'Kabasalan', 'province_id' => 90],
			['id' => 1131, 'name' => 'Mabuhay', 'province_id' => 90],
			['id' => 1132, 'name' => 'Malangas', 'province_id' => 90],
			['id' => 1133, 'name' => 'Naga', 'province_id' => 90],
			['id' => 1134, 'name' => 'Olutanga', 'province_id' => 90],
			['id' => 1135, 'name' => 'Payao', 'province_id' => 90],
			['id' => 1136, 'name' => 'Roseller T. Lim', 'province_id' => 90],
			['id' => 1137, 'name' => 'Siay', 'province_id' => 90],
			['id' => 1138, 'name' => 'Talusan', 'province_id' => 90],
			['id' => 1139, 'name' => 'Titay', 'province_id' => 90],
			['id' => 1140, 'name' => 'Tungawan', 'province_id' => 90],
			['id' => 1141, 'name' => 'Baungon', 'province_id' => 91],
			['id' => 1142, 'name' => 'Cabanglasan', 'province_id' => 91],
			['id' => 1143, 'name' => 'Damulog', 'province_id' => 91],
			['id' => 1144, 'name' => 'Dangcagan', 'province_id' => 91],
			['id' => 1145, 'name' => 'Don Carlos', 'province_id' => 91],
			['id' => 1146, 'name' => 'Impasug-ong', 'province_id' => 91],
			['id' => 1147, 'name' => 'Kadingilan', 'province_id' => 91],
			['id' => 1148, 'name' => 'Kalilangan', 'province_id' => 91],
			['id' => 1149, 'name' => 'Kibawe', 'province_id' => 91],
			['id' => 1150, 'name' => 'Kitaotao', 'province_id' => 91],
			['id' => 1151, 'name' => 'Lantapan', 'province_id' => 91],
			['id' => 1152, 'name' => 'Libona', 'province_id' => 91],
			['id' => 1153, 'name' => 'Malaybalay City', 'province_id' => 91],
			['id' => 1154, 'name' => 'Malitbog', 'province_id' => 91],
			['id' => 1155, 'name' => 'Manolo Fortich', 'province_id' => 91],
			['id' => 1156, 'name' => 'Maramag', 'province_id' => 91],
			['id' => 1157, 'name' => 'Pangantucan', 'province_id' => 91],
			['id' => 1158, 'name' => 'Quezon', 'province_id' => 91],
			['id' => 1159, 'name' => 'San Fernando', 'province_id' => 91],
			['id' => 1160, 'name' => 'Sumilao', 'province_id' => 91],
			['id' => 1161, 'name' => 'Talakag', 'province_id' => 91],
			['id' => 1162, 'name' => 'Valencia City', 'province_id' => 91],
			['id' => 1163, 'name' => 'Cagayan de Oro', 'province_id' => 92],
			['id' => 1164, 'name' => 'Catarman', 'province_id' => 93],
			['id' => 1165, 'name' => 'Guinsiliban', 'province_id' => 93],
			['id' => 1166, 'name' => 'Mahinog', 'province_id' => 93],
			['id' => 1167, 'name' => 'Mambajao', 'province_id' => 93],
			['id' => 1168, 'name' => 'Sagay', 'province_id' => 93],
			['id' => 1169, 'name' => ' Iligan', 'province_id' => 94],
			['id' => 1170, 'name' => 'Bacolod', 'province_id' => 95],
			['id' => 1171, 'name' => 'Baloi', 'province_id' => 95],
			['id' => 1172, 'name' => 'Baroy', 'province_id' => 95],
			['id' => 1173, 'name' => 'Kapatagan', 'province_id' => 95],
			['id' => 1174, 'name' => 'Kauswagan', 'province_id' => 95],
			['id' => 1175, 'name' => 'Kolambugan', 'province_id' => 95],
			['id' => 1176, 'name' => 'Lala', 'province_id' => 95],
			['id' => 1177, 'name' => 'Linamon', 'province_id' => 95],
			['id' => 1178, 'name' => 'Magsaysay', 'province_id' => 95],
			['id' => 1179, 'name' => 'Maigo', 'province_id' => 95],
			['id' => 1180, 'name' => 'Matungao', 'province_id' => 95],
			['id' => 1181, 'name' => 'Munai', 'province_id' => 95],
			['id' => 1182, 'name' => 'Nunungan', 'province_id' => 95],
			['id' => 1183, 'name' => 'Pantao Ragat', 'province_id' => 95],
			['id' => 1184, 'name' => 'Pantar', 'province_id' => 95],
			['id' => 1185, 'name' => 'Poona Piagapo', 'province_id' => 95],
			['id' => 1186, 'name' => 'Salvador', 'province_id' => 95],
			['id' => 1187, 'name' => 'Sapad', 'province_id' => 95],
			['id' => 1188, 'name' => 'Sultan Naga Dimaporo (Karomatan)', 'province_id' => 95],
			['id' => 1189, 'name' => 'Tagoloan', 'province_id' => 95],
			['id' => 1190, 'name' => 'Tangcal', 'province_id' => 95],
			['id' => 1191, 'name' => 'Tubod', 'province_id' => 95],
			['id' => 1192, 'name' => 'Oroquieta City', 'province_id' => 96],
			['id' => 1193, 'name' => 'Ozamiz City', 'province_id' => 96],
			['id' => 1194, 'name' => 'Tangub City', 'province_id' => 96],
			['id' => 1195, 'name' => 'Aloran', 'province_id' => 96],
			['id' => 1196, 'name' => 'Baliangao', 'province_id' => 96],
			['id' => 1197, 'name' => 'Bonifacio', 'province_id' => 96],
			['id' => 1198, 'name' => 'Calamba', 'province_id' => 96],
			['id' => 1199, 'name' => 'Clarin', 'province_id' => 96],
			['id' => 1200, 'name' => 'Concepcion', 'province_id' => 96],
			['id' => 1201, 'name' => 'Don Victoriano Chiongbian (Don Mariano Marcos)', 'province_id' => 96],
			['id' => 1202, 'name' => 'Jimenez', 'province_id' => 96],
			['id' => 1203, 'name' => 'Lopez Jaena', 'province_id' => 96],
			['id' => 1204, 'name' => 'Panaon', 'province_id' => 96],
			['id' => 1205, 'name' => 'Plaridel', 'province_id' => 96],
			['id' => 1206, 'name' => 'Sapang Dalaga', 'province_id' => 96],
			['id' => 1207, 'name' => 'Sinacaban', 'province_id' => 96],
			['id' => 1208, 'name' => 'Tudela', 'province_id' => 96],
			['id' => 1209, 'name' => 'El Salvador City', 'province_id' => 97],
			['id' => 1210, 'name' => 'Gingoog City', 'province_id' => 97],
			['id' => 1211, 'name' => 'Cagayan De Oro City', 'province_id' => 97],
			['id' => 1212, 'name' => 'Alubijid', 'province_id' => 97],
			['id' => 1213, 'name' => 'Balingasag (2nd Class Municipality)', 'province_id' => 97],
			['id' => 1214, 'name' => 'Balingoan', 'province_id' => 97],
			['id' => 1215, 'name' => 'Binuangan', 'province_id' => 97],
			['id' => 1216, 'name' => 'Claveria', 'province_id' => 97],
			['id' => 1217, 'name' => 'Gitagum', 'province_id' => 97],
			['id' => 1218, 'name' => 'Initao', 'province_id' => 97],
			['id' => 1219, 'name' => 'Jasaan', 'province_id' => 97],
			['id' => 1220, 'name' => 'Kinoguitan', 'province_id' => 97],
			['id' => 1221, 'name' => 'Lagonglong', 'province_id' => 97],
			['id' => 1222, 'name' => 'Laguindingan', 'province_id' => 97],
			['id' => 1223, 'name' => 'Libertad', 'province_id' => 97],
			['id' => 1224, 'name' => 'Lugait', 'province_id' => 97],
			['id' => 1225, 'name' => 'Magsaysay', 'province_id' => 97],
			['id' => 1226, 'name' => 'Manticao', 'province_id' => 97],
			['id' => 1227, 'name' => 'Medina', 'province_id' => 97],
			['id' => 1228, 'name' => 'Naawan', 'province_id' => 97],
			['id' => 1229, 'name' => 'Opol', 'province_id' => 97],
			['id' => 1230, 'name' => 'Salay', 'province_id' => 97],
			['id' => 1231, 'name' => 'Sugbongcogon', 'province_id' => 97],
			['id' => 1232, 'name' => 'Tagoloan (1st Class Municipality)', 'province_id' => 97],
			['id' => 1233, 'name' => 'Talisayan', 'province_id' => 97],
			['id' => 1234, 'name' => 'Villanueva', 'province_id' => 97],
			['id' => 1235, 'name' => 'Compostela', 'province_id' => 98],
			['id' => 1236, 'name' => 'Laak', 'province_id' => 98],
			['id' => 1237, 'name' => 'Mabini', 'province_id' => 98],
			['id' => 1238, 'name' => 'Maco', 'province_id' => 98],
			['id' => 1239, 'name' => 'Maragusan', 'province_id' => 98],
			['id' => 1240, 'name' => 'Mawab', 'province_id' => 98],
			['id' => 1241, 'name' => 'Monkayo', 'province_id' => 98],
			['id' => 1242, 'name' => 'Montevista', 'province_id' => 98],
			['id' => 1243, 'name' => 'Nabunturan', 'province_id' => 98],
			['id' => 1244, 'name' => 'New Bataan', 'province_id' => 98],
			['id' => 1245, 'name' => 'Pantukan', 'province_id' => 98],
			['id' => 1246, 'name' => ' Davao City', 'province_id' => 99],
			['id' => 1247, 'name' => 'Asuncion', 'province_id' => 100],
			['id' => 1248, 'name' => 'Braulio E. Dujali', 'province_id' => 100],
			['id' => 1249, 'name' => 'Carmen', 'province_id' => 100],
			['id' => 1250, 'name' => 'Kapalong', 'province_id' => 100],
			['id' => 1251, 'name' => 'New Corella', 'province_id' => 100],
			['id' => 1252, 'name' => 'Panabo City', 'province_id' => 100],
			['id' => 1253, 'name' => 'Samal City', 'province_id' => 100],
			['id' => 1254, 'name' => 'San Isidro', 'province_id' => 100],
			['id' => 1255, 'name' => 'Santo Tomas', 'province_id' => 100],
			['id' => 1256, 'name' => 'Tagum City', 'province_id' => 100],
			['id' => 1257, 'name' => 'Talaingod', 'province_id' => 100],
			['id' => 1258, 'name' => 'Santa Cruz', 'province_id' => 101],
			['id' => 1259, 'name' => 'Bansalan', 'province_id' => 101],
			['id' => 1260, 'name' => 'Matanao', 'province_id' => 101],
			['id' => 1261, 'name' => 'Magsaysay', 'province_id' => 101],
			['id' => 1262, 'name' => 'Hagonoy', 'province_id' => 101],
			['id' => 1263, 'name' => 'Sulop', 'province_id' => 101],
			['id' => 1264, 'name' => 'Padada', 'province_id' => 101],
			['id' => 1265, 'name' => 'Kiblawan', 'province_id' => 101],
			['id' => 1266, 'name' => 'Malalag', 'province_id' => 101],
			['id' => 1267, 'name' => 'Mati City', 'province_id' => 102],
			['id' => 1268, 'name' => 'Baganga', 'province_id' => 102],
			['id' => 1269, 'name' => 'Banaybanay', 'province_id' => 102],
			['id' => 1270, 'name' => 'Boston', 'province_id' => 102],
			['id' => 1271, 'name' => 'Caraga', 'province_id' => 102],
			['id' => 1272, 'name' => 'Cateel', 'province_id' => 102],
			['id' => 1273, 'name' => 'Governor Generoso', 'province_id' => 102],
			['id' => 1274, 'name' => 'Lupon', 'province_id' => 102],
			['id' => 1275, 'name' => 'Manay', 'province_id' => 102],
			['id' => 1276, 'name' => 'San Isidro', 'province_id' => 102],
			['id' => 1277, 'name' => 'Tarragona', 'province_id' => 102],
			['id' => 1278, 'name' => 'Don Marcelino', 'province_id' => 103],
			['id' => 1279, 'name' => 'Jose Abad Santos', 'province_id' => 103],
			['id' => 1280, 'name' => 'Malita', 'province_id' => 103],
			['id' => 1281, 'name' => 'Santa Maria', 'province_id' => 103],
			['id' => 1282, 'name' => 'Sarangani', 'province_id' => 103],
			['id' => 1283, 'name' => 'Alamada', 'province_id' => 104],
			['id' => 1284, 'name' => 'Aleosan', 'province_id' => 104],
			['id' => 1285, 'name' => 'Antipas', 'province_id' => 104],
			['id' => 1286, 'name' => 'Arakan', 'province_id' => 104],
			['id' => 1287, 'name' => 'Banisilan', 'province_id' => 104],
			['id' => 1288, 'name' => 'Carmen', 'province_id' => 104],
			['id' => 1289, 'name' => 'Cotabato City', 'province_id' => 104],
			['id' => 1290, 'name' => 'Kabacan', 'province_id' => 104],
			['id' => 1291, 'name' => 'Kidapawan City', 'province_id' => 104],
			['id' => 1292, 'name' => 'Libungan', 'province_id' => 104],
			['id' => 1293, 'name' => 'Magpet', 'province_id' => 104],
			['id' => 1294, 'name' => 'Makilala', 'province_id' => 104],
			['id' => 1295, 'name' => 'Matalam', 'province_id' => 104],
			['id' => 1296, 'name' => 'Midsayap', 'province_id' => 104],
			['id' => 1297, 'name' => 'Pigkawayan', 'province_id' => 104],
			['id' => 1298, 'name' => 'Pikit', 'province_id' => 104],
			['id' => 1299, 'name' => 'President Roxas', 'province_id' => 104],
			['id' => 1300, 'name' => 'Tulunan', 'province_id' => 104],
			['id' => 1301, 'name' => 'General Santos', 'province_id' => 106],
			['id' => 1302, 'name' => 'Polomolok', 'province_id' => 106],
			['id' => 1303, 'name' => 'Tupi', 'province_id' => 106],
			['id' => 1304, 'name' => 'Tampakan', 'province_id' => 106],
			['id' => 1305, 'name' => 'Alabel', 'province_id' => 107],
			['id' => 1306, 'name' => 'Glan', 'province_id' => 107],
			['id' => 1307, 'name' => 'Kiamba', 'province_id' => 107],
			['id' => 1308, 'name' => 'Maasim', 'province_id' => 107],
			['id' => 1309, 'name' => 'Maitum', 'province_id' => 107],
			['id' => 1310, 'name' => 'Malapatan', 'province_id' => 107],
			['id' => 1311, 'name' => 'Malungon', 'province_id' => 107],
			['id' => 1312, 'name' => 'Polomolok', 'province_id' => 108],
			['id' => 1313, 'name' => 'Tupi', 'province_id' => 108],
			['id' => 1314, 'name' => 'Koronadal', 'province_id' => 108],
			['id' => 1315, 'name' => 'Banga', 'province_id' => 108],
			['id' => 1316, 'name' => 'Lake Sebu', 'province_id' => 108],
			['id' => 1317, 'name' => 'Norala', 'province_id' => 108],
			['id' => 1318, 'name' => 'Sto. Niño', 'province_id' => 108],
			['id' => 1319, 'name' => 'Surallah', 'province_id' => 108],
			['id' => 1320, 'name' => 'Tampakan', 'province_id' => 108],
			['id' => 1321, 'name' => 'Tantangan', 'province_id' => 108],
			['id' => 1322, 'name' => 'Tacurong City', 'province_id' => 109],
			['id' => 1323, 'name' => 'Bagumbayan', 'province_id' => 109],
			['id' => 1324, 'name' => 'Columbio', 'province_id' => 109],
			['id' => 1325, 'name' => 'Esperanza', 'province_id' => 109],
			['id' => 1326, 'name' => 'Isulan', 'province_id' => 109],
			['id' => 1327, 'name' => 'Kalamansig', 'province_id' => 109],
			['id' => 1328, 'name' => 'Lambayong (Mariano Marcos)', 'province_id' => 109],
			['id' => 1329, 'name' => 'Lebak', 'province_id' => 109],
			['id' => 1330, 'name' => 'Lutayan', 'province_id' => 109],
			['id' => 1331, 'name' => 'Palimbang', 'province_id' => 109],
			['id' => 1332, 'name' => 'President Quirino', 'province_id' => 109],
			['id' => 1333, 'name' => 'Sen. Ninoy Aquino', 'province_id' => 109],
			['id' => 1334, 'name' => 'Cabadbaran City', 'province_id' => 110],
			['id' => 1335, 'name' => 'Buenavista', 'province_id' => 110],
			['id' => 1336, 'name' => 'Carmen', 'province_id' => 110],
			['id' => 1337, 'name' => 'Jabonga', 'province_id' => 110],
			['id' => 1338, 'name' => 'Kitcharao', 'province_id' => 110],
			['id' => 1339, 'name' => 'Las Nieves', 'province_id' => 110],
			['id' => 1340, 'name' => 'Magallanes', 'province_id' => 110],
			['id' => 1341, 'name' => 'Nasipit', 'province_id' => 110],
			['id' => 1342, 'name' => 'Remedios T. Romualdez', 'province_id' => 110],
			['id' => 1343, 'name' => 'Santiago', 'province_id' => 110],
			['id' => 1344, 'name' => 'Tubay', 'province_id' => 110],
			['id' => 1345, 'name' => 'Bayugan City', 'province_id' => 111],
			['id' => 1346, 'name' => 'Bunawan', 'province_id' => 111],
			['id' => 1347, 'name' => 'Esperanza', 'province_id' => 111],
			['id' => 1348, 'name' => 'La Paz', 'province_id' => 111],
			['id' => 1349, 'name' => 'Loreto', 'province_id' => 111],
			['id' => 1350, 'name' => 'Prosperidad', 'province_id' => 111],
			['id' => 1351, 'name' => 'Rosario', 'province_id' => 111],
			['id' => 1352, 'name' => 'San Francisco', 'province_id' => 111],
			['id' => 1353, 'name' => 'San Luis', 'province_id' => 111],
			['id' => 1354, 'name' => 'Santa Josefa', 'province_id' => 111],
			['id' => 1355, 'name' => 'Sibagat', 'province_id' => 111],
			['id' => 1356, 'name' => 'Talacogon', 'province_id' => 111],
			['id' => 1357, 'name' => 'Trento', 'province_id' => 111],
			['id' => 1358, 'name' => 'Veruela', 'province_id' => 111],
			['id' => 1359, 'name' => 'Butuan', 'province_id' => 112],
			['id' => 1360, 'name' => 'Basilisa (Rizal)', 'province_id' => 113],
			['id' => 1361, 'name' => 'Cagdianao', 'province_id' => 113],
			['id' => 1362, 'name' => 'Dinagat', 'province_id' => 113],
			['id' => 1363, 'name' => 'Libjo (Albor)', 'province_id' => 113],
			['id' => 1364, 'name' => 'Loreto', 'province_id' => 113],
			['id' => 1365, 'name' => 'Tubajon', 'province_id' => 113],
			['id' => 1366, 'name' => 'San Jose', 'province_id' => 113],
			['id' => 1367, 'name' => 'Surigao City', 'province_id' => 114],
			['id' => 1368, 'name' => 'Alegria', 'province_id' => 114],
			['id' => 1369, 'name' => 'Bacuag', 'province_id' => 114],
			['id' => 1370, 'name' => 'Burgos', 'province_id' => 114],
			['id' => 1371, 'name' => 'Claver', 'province_id' => 114],
			['id' => 1372, 'name' => 'Dapa', 'province_id' => 114],
			['id' => 1373, 'name' => 'Del Carmen', 'province_id' => 114],
			['id' => 1374, 'name' => 'General Luna', 'province_id' => 114],
			['id' => 1375, 'name' => 'Gigaquit', 'province_id' => 114],
			['id' => 1376, 'name' => 'Mainit', 'province_id' => 114],
			['id' => 1377, 'name' => 'Malimono', 'province_id' => 114],
			['id' => 1378, 'name' => 'Pilar', 'province_id' => 114],
			['id' => 1379, 'name' => 'Placer', 'province_id' => 114],
			['id' => 1380, 'name' => 'San Benito', 'province_id' => 114],
			['id' => 1381, 'name' => 'San Francisco (Anao-Aon)', 'province_id' => 114],
			['id' => 1382, 'name' => 'San Isidro', 'province_id' => 114],
			['id' => 1383, 'name' => 'Santa Monica (Sapao)', 'province_id' => 114],
			['id' => 1384, 'name' => 'Sison', 'province_id' => 114],
			['id' => 1385, 'name' => 'Socorro', 'province_id' => 114],
			['id' => 1386, 'name' => 'Tagana-an', 'province_id' => 114],
			['id' => 1387, 'name' => 'Tubod', 'province_id' => 114],
			['id' => 1388, 'name' => 'Tandag City', 'province_id' => 115],
			['id' => 1389, 'name' => 'Bislig City', 'province_id' => 115],
			['id' => 1390, 'name' => 'Barobo', 'province_id' => 115],
			['id' => 1391, 'name' => 'Bayabas', 'province_id' => 115],
			['id' => 1392, 'name' => 'Cagwait', 'province_id' => 115],
			['id' => 1393, 'name' => 'Cantilan', 'province_id' => 115],
			['id' => 1394, 'name' => 'Carmen', 'province_id' => 115],
			['id' => 1395, 'name' => 'Carrascal', 'province_id' => 115],
			['id' => 1396, 'name' => 'Cortes', 'province_id' => 115],
			['id' => 1397, 'name' => 'Hinatuan', 'province_id' => 115],
			['id' => 1398, 'name' => 'Lanuza', 'province_id' => 115],
			['id' => 1399, 'name' => 'Lianga', 'province_id' => 115],
			['id' => 1400, 'name' => 'Lingig', 'province_id' => 115],
			['id' => 1401, 'name' => 'Madrid', 'province_id' => 115],
			['id' => 1402, 'name' => 'Marihatag', 'province_id' => 115],
			['id' => 1403, 'name' => 'San Agustin', 'province_id' => 115],
			['id' => 1404, 'name' => 'San Miguel', 'province_id' => 115],
			['id' => 1405, 'name' => 'Tagbina', 'province_id' => 115],
			['id' => 1406, 'name' => 'Tago', 'province_id' => 115],
			['id' => 1407, 'name' => 'Isabela City1', 'province_id' => 116],
			['id' => 1408, 'name' => 'Lamitan City', 'province_id' => 116],
			['id' => 1409, 'name' => 'Sumisip', 'province_id' => 116],
			['id' => 1410, 'name' => 'Maluso', 'province_id' => 116],
			['id' => 1411, 'name' => 'Lantawan', 'province_id' => 116],
			['id' => 1412, 'name' => 'Al-Barka', 'province_id' => 116],
			['id' => 1413, 'name' => 'Tuburan', 'province_id' => 116],
			['id' => 1414, 'name' => 'Tabuan-Lasa', 'province_id' => 116],
			['id' => 1415, 'name' => 'Ungkaya Pukan', 'province_id' => 116],
			['id' => 1416, 'name' => 'Tipo-Tipo', 'province_id' => 116],
			['id' => 1417, 'name' => 'Hadji Mohammad Ajul', 'province_id' => 116],
			['id' => 1418, 'name' => 'Akbar', 'province_id' => 116],
			['id' => 1419, 'name' => 'Hadji Muhtamad', 'province_id' => 116],
			['id' => 1420, 'name' => 'Marawi City', 'province_id' => 117],
			['id' => 1421, 'name' => 'Bacolod-Kalawi (Bacolod-Grande)', 'province_id' => 117],
			['id' => 1422, 'name' => 'Balabagan', 'province_id' => 117],
			['id' => 1423, 'name' => 'Balindong (WATO)', 'province_id' => 117],
			['id' => 1424, 'name' => 'Bayang', 'province_id' => 117],
			['id' => 1425, 'name' => 'Binidayan', 'province_id' => 117],
			['id' => 1426, 'name' => 'Buadiposo-Buntong', 'province_id' => 117],
			['id' => 1427, 'name' => 'Bubong', 'province_id' => 117],
			['id' => 1428, 'name' => 'Bumbaran', 'province_id' => 117],
			['id' => 1429, 'name' => 'Butig', 'province_id' => 117],
			['id' => 1430, 'name' => 'Calanogas', 'province_id' => 117],
			['id' => 1431, 'name' => 'Ditsaan-Ramain', 'province_id' => 117],
			['id' => 1432, 'name' => 'Ganassi', 'province_id' => 117],
			['id' => 1433, 'name' => 'Kapai', 'province_id' => 117],
			['id' => 1434, 'name' => 'Kapatagan', 'province_id' => 117],
			['id' => 1435, 'name' => 'Lumba-Bayabao', 'province_id' => 117],
			['id' => 1436, 'name' => 'Lumbaca-Unayan', 'province_id' => 117],
			['id' => 1437, 'name' => 'Lumbatan (Macadar)', 'province_id' => 117],
			['id' => 1438, 'name' => 'Lumbayanague (Nanagen)', 'province_id' => 117],
			['id' => 1439, 'name' => 'Madalum', 'province_id' => 117],
			['id' => 1440, 'name' => 'Madamba (Uya-an)', 'province_id' => 117],
			['id' => 1441, 'name' => 'Maguing', 'province_id' => 117],
			['id' => 1442, 'name' => 'Malabang', 'province_id' => 117],
			['id' => 1443, 'name' => 'Marantao(Inudaran)', 'province_id' => 117],
			['id' => 1444, 'name' => 'Marogong', 'province_id' => 117],
			['id' => 1445, 'name' => 'Masiu', 'province_id' => 117],
			['id' => 1446, 'name' => 'Mulondo', 'province_id' => 117],
			['id' => 1447, 'name' => 'Pagayawan', 'province_id' => 117],
			['id' => 1448, 'name' => 'Piagapo', 'province_id' => 117],
			['id' => 1449, 'name' => 'Picong (Sultan Gumander)[1]', 'province_id' => 117],
			['id' => 1450, 'name' => 'Poona Bayabao (Gata)', 'province_id' => 117],
			['id' => 1451, 'name' => 'Pualas', 'province_id' => 117],
			['id' => 1452, 'name' => 'Saguiaran', 'province_id' => 117],
			['id' => 1453, 'name' => 'Sultan Dumalondong (Bacayawan)', 'province_id' => 117],
			['id' => 1454, 'name' => 'Tagoloan II', 'province_id' => 117],
			['id' => 1455, 'name' => 'Tamparan', 'province_id' => 117],
			['id' => 1456, 'name' => 'Taraka', 'province_id' => 117],
			['id' => 1457, 'name' => 'Tubaran', 'province_id' => 117],
			['id' => 1458, 'name' => 'Tugaya', 'province_id' => 117],
			['id' => 1459, 'name' => 'Wao', 'province_id' => 117],
			['id' => 1460, 'name' => 'Ampatuan', 'province_id' => 118],
			['id' => 1461, 'name' => 'Barira', 'province_id' => 118],
			['id' => 1462, 'name' => 'Buldon', 'province_id' => 118],
			['id' => 1463, 'name' => 'Buluan', 'province_id' => 118],
			['id' => 1464, 'name' => 'Datu Abdullah Sangki', 'province_id' => 118],
			['id' => 1465, 'name' => 'Datu Anggal Midtimbang', 'province_id' => 118],
			['id' => 1466, 'name' => 'Datu Blah T. Sinsuat', 'province_id' => 118],
			['id' => 1467, 'name' => 'Datu Hoffer Ampatuan', 'province_id' => 118],
			['id' => 1468, 'name' => 'Datu Odin Sinsuat', 'province_id' => 118],
			['id' => 1469, 'name' => 'Datu Paglas', 'province_id' => 118],
			['id' => 1470, 'name' => 'Datu Piang (Dulawan)', 'province_id' => 118],
			['id' => 1471, 'name' => 'Datu Salibo', 'province_id' => 118],
			['id' => 1472, 'name' => 'Datu Saudi-Ampatuan', 'province_id' => 118],
			['id' => 1473, 'name' => 'Datu Unsay', 'province_id' => 118],
			['id' => 1474, 'name' => 'Gen. S. K. Pendatun', 'province_id' => 118],
			['id' => 1475, 'name' => 'Guindulungan', 'province_id' => 118],
			['id' => 1476, 'name' => 'Kabuntalan', 'province_id' => 118],
			['id' => 1477, 'name' => 'Mamasapano', 'province_id' => 118],
			['id' => 1478, 'name' => 'Mangudadatu', 'province_id' => 118],
			['id' => 1479, 'name' => 'Matanog', 'province_id' => 118],
			['id' => 1480, 'name' => 'Northern Kabuntalan', 'province_id' => 118],
			['id' => 1481, 'name' => 'Pagagawan (Datu Montawal)', 'province_id' => 118],
			['id' => 1482, 'name' => 'Pagalungan', 'province_id' => 118],
			['id' => 1483, 'name' => 'Paglat', 'province_id' => 118],
			['id' => 1484, 'name' => 'Pandag', 'province_id' => 118],
			['id' => 1485, 'name' => 'Parang', 'province_id' => 118],
			['id' => 1486, 'name' => 'Rajah Buayan', 'province_id' => 118],
			['id' => 1487, 'name' => 'Shariff Aguak (Maganoy)', 'province_id' => 118],
			['id' => 1488, 'name' => 'Shariff Saydona Mustapha', 'province_id' => 118],
			['id' => 1489, 'name' => 'South Upi', 'province_id' => 118],
			['id' => 1490, 'name' => 'Sultan Kudarat (Nuling)', 'province_id' => 118],
			['id' => 1491, 'name' => 'Sultan Mastura', 'province_id' => 118],
			['id' => 1492, 'name' => 'Sultan sa Barongis (Lambayong)', 'province_id' => 118],
			['id' => 1493, 'name' => 'Sultan Sumagka (Talitay)', 'province_id' => 118],
			['id' => 1494, 'name' => 'Talayan', 'province_id' => 118],
			['id' => 1495, 'name' => 'Upi', 'province_id' => 118],
			['id' => 1496, 'name' => 'Banguingui (Tongkil)', 'province_id' => 119],
			['id' => 1497, 'name' => 'Hadji Panglima Tahil (Marunggas)', 'province_id' => 119],
			['id' => 1498, 'name' => 'Indanan', 'province_id' => 119],
			['id' => 1499, 'name' => 'Jolo', 'province_id' => 119],
			['id' => 1500, 'name' => 'Kalingalan Caluang', 'province_id' => 119],
			['id' => 1501, 'name' => 'Lugus', 'province_id' => 119],
			['id' => 1502, 'name' => 'Luuk', 'province_id' => 119],
			['id' => 1503, 'name' => 'Maimbung', 'province_id' => 119],
			['id' => 1504, 'name' => 'Old Panamao', 'province_id' => 119],
			['id' => 1505, 'name' => 'Omar', 'province_id' => 119],
			['id' => 1506, 'name' => 'Pandami', 'province_id' => 119],
			['id' => 1507, 'name' => 'Panglima Estino (New Panamao)', 'province_id' => 119],
			['id' => 1508, 'name' => 'Pangutaran', 'province_id' => 119],
			['id' => 1509, 'name' => 'Parang', 'province_id' => 119],
			['id' => 1510, 'name' => 'Pata', 'province_id' => 119],
			['id' => 1511, 'name' => 'Patikul', 'province_id' => 119],
			['id' => 1512, 'name' => 'Siasi', 'province_id' => 119],
			['id' => 1513, 'name' => 'Talipao', 'province_id' => 119],
			['id' => 1514, 'name' => 'Tapul', 'province_id' => 119],
			['id' => 1515, 'name' => 'Bongao', 'province_id' => 120],
			['id' => 1516, 'name' => 'Languyan ', 'province_id' => 120],
			['id' => 1517, 'name' => 'Mapun', 'province_id' => 120],
			['id' => 1518, 'name' => 'Panglima Sugala', 'province_id' => 120],
			['id' => 1519, 'name' => 'Sapa-Sapa', 'province_id' => 120],
			['id' => 1520, 'name' => 'Sibutu', 'province_id' => 120],
			['id' => 1521, 'name' => 'Simunul', 'province_id' => 120],
			['id' => 1522, 'name' => 'Sitangkai', 'province_id' => 120],
			['id' => 1523, 'name' => 'South Ubian', 'province_id' => 120],
			['id' => 1524, 'name' => 'Tandubas', 'province_id' => 120],
			['id' => 1525, 'name' => 'Turtle Islands', 'province_id' => 120],
			['id' => 1526, 'name' => 'Sta. Maria', 'province_id' => 38],
			['id' => 1527, 'name' => 'Guang Zhou', 'province_id' => 122],
		]);

		// City::insert([
		// 	['name'=> 'Lawitan', 			'region_id' => 1],
		// 	['name'=> 'Marawi', 			'region_id' => 1],
		// 	['name'=> 'Baguio', 			'region_id' => 2],
		// 	['name'=> 'Tabuk', 				'region_id' => 2],
		// 	['name' => 'Caloocan', 			'region_id' => 3],
		// 	['name' => 'Las Piñas', 		'region_id' => 3],
		// 	['name' => 'Makati', 			'region_id' => 3],
		// 	['name' => 'Malabon', 			'region_id' => 3],
		// 	['name' => 'Mandaluyong', 		'region_id' => 3],
		// 	['name' => 'Manila', 			'region_id' => 3],
		// 	['name' => 'Marikina', 			'region_id' => 3],
		// 	['name' => 'Muntinlupa', 		'region_id' => 3],
		// 	['name' => 'Navotas', 			'region_id' => 3],
		// 	['name' => 'Parañaque', 		'region_id' => 3],
		// 	['name' => 'Pasay', 			'region_id' => 3],
		// 	['name' => 'Pasig', 			'region_id' => 3],
		// 	['name' => 'Quezon', 			'region_id' => 3],
		// 	['name' => 'San Juan', 			'region_id' => 3],
		// 	['name' => 'Taguig', 			'region_id' => 3],
		// 	['name' => 'Valenzuela', 		'region_id' => 3],
		// 	['name' => 'Batac',				'region_id' => 4],
		// 	['name' => 'Laoag',				'region_id' => 4],
		// 	['name' => 'Candon',			'region_id' => 4],
		// 	['name' => 'Vigan',				'region_id' => 4],
		// 	['name' => 'San Fernando',		'region_id' => 4],
		// 	['name' => 'Alaminos',			'region_id' => 4],
		// 	['name' => 'Dagupan',			'region_id' => 4],
		// 	['name' => 'San Carlos',		'region_id' => 4],
		// 	['name' => 'Urdaneta',			'region_id' => 4],
		// 	['name' => 'Tuguegarao', 		'region_id' => 5],
		// 	['name' => 'Cauayan', 			'region_id' => 5],
		// 	['name' => 'Ilagan', 			'region_id' => 5],
		// 	['name' => 'Santiago', 			'region_id' => 5],
		// 	['name' => 'Balanga', 			'region_id' => 6],
		// 	['name' => 'Malolos', 			'region_id' => 6],
		// 	['name' => 'Meycauayan', 		'region_id' => 6],
		// 	['name' => 'San Jose del Monte','region_id' => 6],
		// 	['name' => 'Cabanatuan', 		'region_id' => 6],
		// 	['name' => 'Gapan', 			'region_id' => 6],
		// 	['name' => 'Muñoz', 			'region_id' => 6],
		// 	['name' => 'Palayan', 			'region_id' => 6],
		// 	['name' => 'Angeles', 			'region_id' => 6],
		// 	['name' => 'Mabalacat', 		'region_id' => 6],
		// 	['name' => 'San Fernando', 		'region_id' => 6],
		// 	['name' => 'Tarlac', 			'region_id' => 6],
		// 	['name' => 'Olongapo', 			'region_id' => 6],
		// 	['name' => 'San Jose', 			'region_id' => 6],
		// 	['name' => 'Batangas', 			'region_id' => 7],
		// 	['name' => 'Lipa', 				'region_id' => 7],
		// 	['name' => 'Tanauan', 			'region_id' => 7],
		// 	['name' => 'Bacoor', 			'region_id' => 7],
		// 	['name' => 'Cavite', 			'region_id' => 7],
		// 	['name' => 'Dasmariñas', 		'region_id' => 7],
		// 	['name' => 'Imus', 				'region_id' => 7],
		// 	['name' => 'Tagaytay', 			'region_id' => 7],
		// 	['name' => 'Trece Martires', 	'region_id' => 7],
		// 	['name' => 'Biñan', 			'region_id' => 7],
		// 	['name' => 'Cabuyao', 			'region_id' => 7],
		// 	['name' => 'San Pablo', 		'region_id' => 7],
		// 	['name' => 'Santa Rosa', 		'region_id' => 7],
		// 	['name' => 'Lucena', 			'region_id' => 7],
		// 	['name' => 'Tayabas', 			'region_id' => 7],
		// 	['name' => 'Antipolo', 			'region_id' => 7],
		// 	['name' => 'Calamba', 			'region_id' => 7],
		// 	['name' => 'Calapan',			'region_id' => 8],
		// 	['name' => 'Puerto Princesa', 	'region_id' => 8],
		// ]);
}
}
